const CONCERTS_DATA = [
  // === SPACED - UK AND IRELAND 2026 ===
  {"date":"2025-09-08","artist":"Spaced","support":"","city":"Newcastle","country":"UK","venue":"The Grove","tour":"UK and Ireland 2026","ticketUrl":"https://lnk.to/SPACED-NEWCASTLE26"},
  {"date":"2025-09-09","artist":"Spaced","support":"","city":"Leeds","country":"UK","venue":"Boom","tour":"UK and Ireland 2026","ticketUrl":"https://lnk.to/SPACED-LEEDS2026"},
  {"date":"2025-09-10","artist":"Spaced","support":"","city":"London","country":"UK","venue":"Underworld","tour":"UK and Ireland 2026","ticketUrl":"https://lnk.to/SPACED-LONDON26"},
  {"date":"2026-08-29","artist":"Spaced","support":"","city":"Cork","country":"Ireland","venue":"Dali","tour":"UK and Ireland 2026","ticketUrl":"https://lnk.to/SPACED-CORK26"},
  {"date":"2026-08-30","artist":"Spaced","support":"","city":"Dublin","country":"Ireland","venue":"Lost Lane","tour":"UK and Ireland 2026","ticketUrl":"https://lnk.to/SPACED-DUBLIN26"},
  {"date":"2026-08-31","artist":"Spaced","support":"","city":"Belfast","country":"UK","venue":"Voodoo","tour":"UK and Ireland 2026","ticketUrl":"https://lnk.to/SPACED-BELFAST26"},
  {"date":"2026-09-02","artist":"Spaced","support":"","city":"Bristol","country":"UK","venue":"Exchange","tour":"UK and Ireland 2026","ticketUrl":"https://lnk.to/SPACED-BRISTOL26"},
  {"date":"2026-09-03","artist":"Spaced","support":"","city":"Swansea","country":"UK","venue":"The Bunkhouse","tour":"UK and Ireland 2026","ticketUrl":"https://lnk.to/SPACED-SWANSEA26"},
  {"date":"2026-09-04","artist":"Spaced","support":"","city":"Torquay","country":"UK","venue":"Burn it Down Festival","tour":"UK and Ireland 2026","ticketUrl":"https://www.byplive.co.uk/burn-it-down"},
  {"date":"2026-09-05","artist":"Spaced","support":"","city":"Liverpool","country":"UK","venue":"No Play Festival","tour":"UK and Ireland 2026","ticketUrl":"https://www.instagram.com/noplayfest/"},
  {"date":"2026-09-06","artist":"Spaced","support":"","city":"Glasgow","country":"UK","venue":"Mono","tour":"UK and Ireland 2026","ticketUrl":"https://lnk.to/SPACED-GLASGOW26"},

  // === CRYSTAL LAKE & MISS MAY I - EUROPEAN TOUR 2026 ===
  {"date":"2026-02-24","artist":"Crystal Lake & Miss May I","support":"Great American Ghost, Diesect","city":"Utrecht","country":"Netherlands","venue":"Tivoli Pandora","tour":"European Tour 2026","ticketUrl":"http://lnk.to/CL-MMI-Utrecht"},
  {"date":"2026-02-25","artist":"Crystal Lake & Miss May I","support":"Great American Ghost, Diesect","city":"Antwerp","country":"Belgium","venue":"Zappa","tour":"European Tour 2026","ticketUrl":"http://lnk.to/CL-MMI-Antwerp"},
  {"date":"2026-02-27","artist":"Crystal Lake & Miss May I","support":"Great American Ghost, Diesect","city":"Karlsruhe","country":"Germany","venue":"Substage","tour":"European Tour 2026","ticketUrl":"http://lnk.to/CL-MMI-Karlsruhe"},
  {"date":"2026-02-28","artist":"Crystal Lake & Miss May I","support":"Great American Ghost, Diesect","city":"Cologne","country":"Germany","venue":"Essigfabrik","tour":"European Tour 2026","ticketUrl":"http://lnk.to/CL-MMI-Cologne"},
  {"date":"2026-03-01","artist":"Crystal Lake & Miss May I","support":"Great American Ghost, Diesect","city":"Hamburg","country":"Germany","venue":"Logo","tour":"European Tour 2026","ticketUrl":"http://lnk.to/CL-MMI-Hamburg"},
  {"date":"2026-03-02","artist":"Crystal Lake & Miss May I","support":"Great American Ghost, Diesect","city":"Berlin","country":"Germany","venue":"SO36","tour":"European Tour 2026","ticketUrl":"http://lnk.to/CL-MMI-Berlin"},
  {"date":"2026-03-03","artist":"Crystal Lake & Miss May I","support":"Great American Ghost, Diesect","city":"Prague","country":"Czech Republic","venue":"Rock Cafe","tour":"European Tour 2026","ticketUrl":"http://lnk.to/CL-MMI-Prague"},
  {"date":"2026-03-05","artist":"Crystal Lake & Miss May I","support":"Great American Ghost, Diesect","city":"Vienna","country":"Austria","venue":"Flex Café","tour":"European Tour 2026","ticketUrl":"http://lnk.to/CL-MMI-Vienna"},
  {"date":"2026-03-06","artist":"Crystal Lake & Miss May I","support":"Great American Ghost, Diesect","city":"Munich","country":"Germany","venue":"Backstage","tour":"European Tour 2026","ticketUrl":"http://lnk.to/CL-MMI-Munich"},
  {"date":"2026-03-07","artist":"Crystal Lake & Miss May I","support":"Great American Ghost, Diesect","city":"Geneva","country":"Switzerland","venue":"PTR/L’Usine","tour":"European Tour 2026","ticketUrl":"http://lnk.to/CL-MMI-Geneva"},
  {"date":"2026-03-09","artist":"Crystal Lake & Miss May I","support":"Great American Ghost, Diesect","city":"Barcelona","country":"Spain","venue":"Razzmatazz 2","tour":"European Tour 2026","ticketUrl":"http://lnk.to/CL-MMI-Barcelona"},
  {"date":"2026-03-10","artist":"Crystal Lake & Miss May I","support":"Great American Ghost, Diesect","city":"Madrid","country":"Spain","venue":"Copérnico","tour":"European Tour 2026","ticketUrl":"http://lnk.to/CL-MMI-Madrid"},
  {"date":"2026-03-11","artist":"Crystal Lake & Miss May I","support":"Great American Ghost, Diesect","city":"Lisbon","country":"Portugal","venue":"LAV Lisboa ao Vivo","tour":"European Tour 2026","ticketUrl":"http://lnk.to/CL-MMI-Lisbon"},
  {"date":"2026-03-12","artist":"Crystal Lake & Miss May I","support":"Great American Ghost, Diesect","city":"Vitoria","country":"Spain","venue":"Jimmy Jazz","tour":"European Tour 2026","ticketUrl":"http://lnk.to/CL-MMI-Vitoria"},
  {"date":"2026-03-14","artist":"Crystal Lake & Miss May I","support":"Great American Ghost, Diesect","city":"Paris","country":"France","venue":"Nouveau Casino","tour":"European Tour 2026","ticketUrl":"http://lnk.to/CL-MMI-Paris"},
  {"date":"2026-03-15","artist":"Crystal Lake & Miss May I","support":"Great American Ghost, Diesect","city":"Lille","country":"France","venue":"The Black Lab","tour":"European Tour 2026","ticketUrl":"http://lnk.to/CL-MMI-Lille"},
  {"date":"2026-03-16","artist":"Crystal Lake & Miss May I","support":"Great American Ghost, Diesect","city":"Southampton","country":"UK","venue":"The Brook","tour":"European Tour 2026","ticketUrl":"http://lnk.to/CL-MMI-Southampton"},
  {"date":"2026-03-17","artist":"Crystal Lake & Miss May I","support":"Great American Ghost, Diesect","city":"Cardiff","country":"UK","venue":"Tramshed","tour":"European Tour 2026","ticketUrl":"http://lnk.to/CL-MMI-Cardiff"},
  {"date":"2026-03-19","artist":"Crystal Lake & Miss May I","support":"Great American Ghost, Diesect","city":"London","country":"UK","venue":"O2 Academy Islington","tour":"European Tour 2026","ticketUrl":"http://lnk.to/CL-MMI-London"},
  {"date":"2026-03-20","artist":"Crystal Lake & Miss May I","support":"Great American Ghost, Diesect","city":"Manchester","country":"UK","venue":"Club Academy","tour":"European Tour 2026","ticketUrl":"http://lnk.to/CL-MMI-Manchester"},
  {"date":"2026-03-21","artist":"Crystal Lake & Miss May I","support":"Great American Ghost, Diesect","city":"Glasgow","country":"UK","venue":"The Garage","tour":"European Tour 2026","ticketUrl":"http://lnk.to/CL-MMI-Glasgow"},
  {"date":"2026-03-22","artist":"Crystal Lake & Miss May I","support":"Great American Ghost, Diesect","city":"Birmingham","country":"UK","venue":"O2 Academy2","tour":"European Tour 2026","ticketUrl":"http://lnk.to/CL-MMI-Birmingham"},

  // === BODYSNATCHER - THE HELL IS HERE, HELL IS HOME TOUR ===
  {"date":"2026-03-04","artist":"Bodysnatcher","support":"Ingested, Psycho-Frame, Big Ass Truck","city":"Southampton","country":"UK","venue":"Engine Rooms","tour":"THE HELL IS HERE, HELL IS HOME TOUR","ticketUrl":"https://lnk.to/Bodysnatcher2026-Southampton"},
  {"date":"2026-03-05","artist":"Bodysnatcher","support":"Ingested, Psycho-Frame, Big Ass Truck","city":"Bristol","country":"UK","venue":"The Fleece","tour":"THE HELL IS HERE, HELL IS HOME TOUR","ticketUrl":"","soldOut":true},
  {"date":"2026-03-06","artist":"Bodysnatcher","support":"Ingested, Psycho-Frame, Big Ass Truck","city":"Manchester","country":"UK","venue":"Club Academy","tour":"THE HELL IS HERE, HELL IS HOME TOUR","ticketUrl":"https://lnk.to/Bodysnatcher2026-Manchester"},
  {"date":"2026-03-07","artist":"Bodysnatcher","support":"Ingested, Psycho-Frame, Big Ass Truck","city":"Glasgow","country":"UK","venue":"Slay","tour":"THE HELL IS HERE, HELL IS HOME TOUR","ticketUrl":"https://lnk.to/Bodysnatcher2026-Glasgow"},
  {"date":"2026-03-09","artist":"Bodysnatcher","support":"Ingested, Psycho-Frame, Big Ass Truck","city":"Belfast","country":"UK","venue":"Limelight 2","tour":"THE HELL IS HERE, HELL IS HOME TOUR","ticketUrl":"https://lnk.to/Bodysnatcher2026-Belfast"},
  {"date":"2026-03-10","artist":"Bodysnatcher","support":"Ingested, Psycho-Frame, Big Ass Truck","city":"Dublin","country":"Ireland","venue":"Whelans","tour":"THE HELL IS HERE, HELL IS HOME TOUR","ticketUrl":"https://lnk.to/Bodysnatcher2026-Dublin"},
  {"date":"2026-03-11","artist":"Bodysnatcher","support":"Ingested, Psycho-Frame, Big Ass Truck","city":"Leeds","country":"UK","venue":"The Key Club","tour":"THE HELL IS HERE, HELL IS HOME TOUR","ticketUrl":"","soldOut":true},
  {"date":"2026-03-12","artist":"Bodysnatcher","support":"Ingested, Psycho-Frame, Big Ass Truck","city":"Nottingham","country":"UK","venue":"Rescue Rooms","tour":"THE HELL IS HERE, HELL IS HOME TOUR","ticketUrl":"https://lnk.to/Bodysnatcher2026-Nottingham"},
  {"date":"2026-03-13","artist":"Bodysnatcher","support":"Ingested, Psycho-Frame, Big Ass Truck","city":"Birmingham","country":"UK","venue":"Asylum","tour":"THE HELL IS HERE, HELL IS HOME TOUR","ticketUrl":"https://lnk.to/Bodysnatcher2026-Birmingham"},
  {"date":"2026-03-14","artist":"Bodysnatcher","support":"Ingested, Psycho-Frame, Big Ass Truck","city":"Plymouth","country":"UK","venue":"The Depo","tour":"THE HELL IS HERE, HELL IS HOME TOUR","ticketUrl":"https://lnk.to/Bodysnatcher2026-Plymouth"},
  {"date":"2026-03-15","artist":"Bodysnatcher","support":"Ingested, Psycho-Frame, Big Ass Truck","city":"London","country":"UK","venue":"The Garage","tour":"THE HELL IS HERE, HELL IS HOME TOUR","ticketUrl":"https://lnk.to/Bodysnatcher2026-London"},
  {"date":"2026-03-17","artist":"Bodysnatcher","support":"Ingested, Psycho-Frame, Big Ass Truck","city":"Berlin","country":"Germany","venue":"Hole44","tour":"THE HELL IS HERE, HELL IS HOME TOUR","ticketUrl":"https://lnk.to/Bodysnatcher2026-Berlin"},
  {"date":"2026-03-18","artist":"Bodysnatcher","support":"Ingested, Psycho-Frame, Big Ass Truck","city":"Copenhagen","country":"Denmark","venue":"Pumpehuset","tour":"THE HELL IS HERE, HELL IS HOME TOUR","ticketUrl":"https://lnk.to/Bodysnatcher2026-Copenhagen"},
  {"date":"2026-03-19","artist":"Bodysnatcher","support":"Ingested, Psycho-Frame, Big Ass Truck","city":"Hamburg","country":"Germany","venue":"Logo","tour":"THE HELL IS HERE, HELL IS HOME TOUR","ticketUrl":"https://lnk.to/Bodysnatcher2026-Hamburg"},
  {"date":"2026-03-20","artist":"Bodysnatcher","support":"Ingested, Psycho-Frame, Big Ass Truck","city":"Hannover","country":"Germany","venue":"Faust","tour":"THE HELL IS HERE, HELL IS HOME TOUR","ticketUrl":"https://lnk.to/Bodysnatcher2026-Hannover"},
  {"date":"2026-03-21","artist":"Bodysnatcher","support":"Ingested, Psycho-Frame, Big Ass Truck","city":"Prague","country":"Czech Republic","venue":"Rock Cafe","tour":"THE HELL IS HERE, HELL IS HOME TOUR","ticketUrl":"https://lnk.to/Bodysnatcher2026-Prague"},
  {"date":"2026-03-22","artist":"Bodysnatcher","support":"Ingested, Psycho-Frame, Big Ass Truck","city":"Warsaw","country":"Poland","venue":"Hydrozagadka","tour":"THE HELL IS HERE, HELL IS HOME TOUR","ticketUrl":"https://lnk.to/Bodysnatcher2026-Warsaw"},
  {"date":"2026-03-24","artist":"Bodysnatcher","support":"Ingested, Psycho-Frame, Big Ass Truck","city":"Vienna","country":"Austria","venue":"Szene","tour":"THE HELL IS HERE, HELL IS HOME TOUR","ticketUrl":"https://lnk.to/Bodysnatcher2026-Vienna"},
  {"date":"2026-03-25","artist":"Bodysnatcher","support":"Ingested, Psycho-Frame, Big Ass Truck","city":"Munich","country":"Germany","venue":"Backstage","tour":"THE HELL IS HERE, HELL IS HOME TOUR","ticketUrl":"https://lnk.to/Bodysnatcher2026-Munich"},
  {"date":"2026-03-26","artist":"Bodysnatcher","support":"Ingested, Psycho-Frame, Big Ass Truck","city":"Aarau","country":"Switzerland","venue":"KiFF","tour":"THE HELL IS HERE, HELL IS HOME TOUR","ticketUrl":"https://lnk.to/Bodysnatcher2026-Aarau"},
  {"date":"2026-03-27","artist":"Bodysnatcher","support":"Ingested, Psycho-Frame, Big Ass Truck","city":"Eindhoven","country":"Netherlands","venue":"Dynamo","tour":"THE HELL IS HERE, HELL IS HOME TOUR","ticketUrl":"https://lnk.to/Bodysnatcher2026-Eindhoven"},
  {"date":"2026-03-28","artist":"Bodysnatcher","support":"Ingested, Psycho-Frame, Big Ass Truck","city":"Bochum","country":"Germany","venue":"Matrix","tour":"THE HELL IS HERE, HELL IS HOME TOUR","ticketUrl":"https://lnk.to/Bodysnatcher2026-Bochum"},
  {"date":"2026-03-29","artist":"Bodysnatcher","support":"Ingested, Psycho-Frame, Big Ass Truck","city":"Antwerp","country":"Belgium","venue":"Trix Club","tour":"THE HELL IS HERE, HELL IS HOME TOUR","ticketUrl":"https://lnk.to/Bodysnatcher2026-Antwerp"},

  // === FRENCH POLICE - EUROPE 2026 ===
  {"date":"2026-03-06","artist":"French Police","support":"Sad Madona","city":"Haarlem","country":"Netherlands","venue":"Patronaat","tour":"Europe 2026","ticketUrl":"http://lnk.to/FrenchPolice2026-Haarlem"},
  {"date":"2026-03-07","artist":"French Police","support":"Sad Madona","city":"Eindhoven","country":"Netherlands","venue":"Effenaar","tour":"Europe 2026","ticketUrl":"http://lnk.to/FrenchPolice2026-Eindhoven"},
  {"date":"2026-03-08","artist":"French Police","support":"Sad Madona","city":"Paris","country":"France","venue":"Petit Bain","tour":"Europe 2026","ticketUrl":"http://lnk.to/FrenchPolice2026-Paris"},
  {"date":"2026-03-10","artist":"French Police","support":"Sad Madona","city":"Bristol","country":"UK","venue":"Thekla","tour":"Europe 2026","ticketUrl":"http://lnk.to/FrenchPolice2026-Bristol"},
  {"date":"2026-03-11","artist":"French Police","support":"Sad Madona","city":"Nottingham","country":"UK","venue":"The Bodega","tour":"Europe 2026","ticketUrl":"http://lnk.to/FrenchPolice2026-Nottingham"},
  {"date":"2026-03-12","artist":"French Police","support":"Sad Madona","city":"Glasgow","country":"UK","venue":"King Tuts","tour":"Europe 2026","ticketUrl":"http://lnk.to/FrenchPolice2026-Glasgow"},
  {"date":"2026-03-13","artist":"French Police","support":"Sad Madona","city":"Manchester","country":"UK","venue":"Deaf Institute","tour":"Europe 2026","ticketUrl":"http://lnk.to/FrenchPolice2026-Manchester"},
  {"date":"2026-03-14","artist":"French Police","support":"Sad Madona","city":"London","country":"UK","venue":"O2 Academy2 Islington","tour":"Europe 2026","ticketUrl":"http://lnk.to/FrenchPolice2026-London"},
  {"date":"2026-03-17","artist":"French Police","support":"Sad Madona","city":"Nantes","country":"France","venue":"Le Ferrailleur","tour":"Europe 2026","ticketUrl":"http://lnk.to/FrenchPolice2026-Nantes"},
  {"date":"2026-03-18","artist":"French Police","support":"Sad Madona","city":"Bordeaux","country":"France","venue":"Deus Ex Machina","tour":"Europe 2026","ticketUrl":""},
  {"date":"2026-03-19","artist":"French Police","support":"Sad Madona","city":"Madrid","country":"Spain","venue":"Wurlitzer Ballroom","tour":"Europe 2026","ticketUrl":"http://lnk.to/FrenchPolice2026-Madrid"},
  {"date":"2026-03-20","artist":"French Police","support":"Sad Madona","city":"Barcelona","country":"Spain","venue":"Razzmatazz 3","tour":"Europe 2026","ticketUrl":"http://lnk.to/FrenchPolice2026-Barcelona"},
  {"date":"2026-03-21","artist":"French Police","support":"Sad Madona","city":"Lyon","country":"France","venue":"La Marquise","tour":"Europe 2026","ticketUrl":"http://lnk.to/FrenchPolice2026-Lyon"},
  {"date":"2026-03-22","artist":"French Police","support":"Sad Madona","city":"Milan","country":"Italy","venue":"Legend Club","tour":"Europe 2026","ticketUrl":"http://lnk.to/FrenchPolice2026-Milan"},
  {"date":"2026-03-23","artist":"French Police","support":"Sad Madona","city":"Munich","country":"Germany","venue":"Feierwerk","tour":"Europe 2026","ticketUrl":"http://lnk.to/FrenchPolice2026-Munich"},
  {"date":"2026-03-25","artist":"French Police","support":"Sad Madona","city":"Prague","country":"Czech Republic","venue":"Bike Jesus","tour":"Europe 2026","ticketUrl":"http://lnk.to/FrenchPolice2026-Prague"},
  {"date":"2026-03-26","artist":"French Police","support":"Sad Madona","city":"Poznan","country":"Poland","venue":"Pod Minoga","tour":"Europe 2026","ticketUrl":"http://lnk.to/FrenchPolice2026-Poznan"},
  {"date":"2026-03-27","artist":"French Police","support":"Sad Madona","city":"Berlin","country":"Germany","venue":"Neue Zukunft","tour":"Europe 2026","ticketUrl":"http://lnk.to/FrenchPolice2026-Berlin"},
  {"date":"2026-03-28","artist":"French Police","support":"Sad Madona","city":"Hamburg","country":"Germany","venue":"Indra","tour":"Europe 2026","ticketUrl":"http://lnk.to/FrenchPolice2026-Hamburg"},
  {"date":"2026-03-29","artist":"French Police","support":"Sad Madona","city":"Cologne","country":"Germany","venue":"Gebäude 9","tour":"Europe 2026","ticketUrl":"http://lnk.to/FrenchPolice2026-Cologne"},

  // === LOST SOCIETY - TOUR IS A STATE OF MIND ===
  {"date":"2026-03-07","artist":"Lost Society","support":"","city":"Cologne","country":"Germany","venue":"Gebäude 9","tour":"Tour Is A State Of Mind","ticketUrl":"https://lnk.to/LS-Cologne26"},
  {"date":"2026-03-09","artist":"Lost Society","support":"","city":"Bristol","country":"UK","venue":"Exchange","tour":"Tour Is A State Of Mind","ticketUrl":"https://lnk.to/LS-Bristol26"},
  {"date":"2026-03-10","artist":"Lost Society","support":"","city":"Manchester","country":"UK","venue":"The Star & Garter","tour":"Tour Is A State Of Mind","ticketUrl":"https://lnk.to/LS-Manc26"},
  {"date":"2026-03-11","artist":"Lost Society","support":"","city":"London","country":"UK","venue":"Underworld","tour":"Tour Is A State Of Mind","ticketUrl":"https://lnk.to/LS-LNDN26"},
  {"date":"2026-03-13","artist":"Lost Society","support":"","city":"Hoofddorp","country":"Netherlands","venue":"Cpunt","tour":"Tour Is A State Of Mind","ticketUrl":"https://lnk.to/LS-Hoofddorp26"},
  {"date":"2026-03-15","artist":"Lost Society","support":"","city":"Aarau","country":"Switzerland","venue":"Kiff","tour":"Tour Is A State Of Mind","ticketUrl":"https://lnk.to/LS-Aarau26"},
  {"date":"2026-03-16","artist":"Lost Society","support":"","city":"Wiesbaden","country":"Germany","venue":"Schlachthof","tour":"Tour Is A State Of Mind","ticketUrl":"https://lnk.to/LS-Wiesbaden26"},
  {"date":"2026-03-17","artist":"Lost Society","support":"","city":"Munich","country":"Germany","venue":"Backstage","tour":"Tour Is A State Of Mind","ticketUrl":"https://lnk.to/LS-MUC26"},
  {"date":"2026-03-18","artist":"Lost Society","support":"","city":"Berlin","country":"Germany","venue":"Cassiopeia","tour":"Tour Is A State Of Mind","ticketUrl":"https://lnk.to/LS-BRLN26"},
  {"date":"2026-03-19","artist":"Lost Society","support":"","city":"Hamburg","country":"Germany","venue":"Betty","tour":"Tour Is A State Of Mind","ticketUrl":"https://lnk.to/LS-HMBRG26"},
  {"date":"2026-03-20","artist":"Lost Society","support":"","city":"Copenhagen","country":"Denmark","venue":"Vega","tour":"Tour Is A State Of Mind","ticketUrl":"https://lnk.to/LS-CPNHGN26"},
  {"date":"2026-03-21","artist":"Lost Society","support":"","city":"Oslo","country":"Norway","venue":"Sub Scene","tour":"Tour Is A State Of Mind","ticketUrl":"https://lnk.to/LostSociety-OSLO26"},
  {"date":"2026-03-22","artist":"Lost Society","support":"","city":"Gothenburg","country":"Sweden","venue":"Monument","tour":"Tour Is A State Of Mind","ticketUrl":"https://lnk.to/LS-GTHNBRG26"},
  {"date":"2026-03-23","artist":"Lost Society","support":"","city":"Stockholm","country":"Sweden","venue":"Debaser Nova","tour":"Tour Is A State Of Mind","ticketUrl":"https://lnk.to/LS-STCKHLM26"},

  // === FIT FOR A KING - LONELY GOD EUROPEAN TOUR 2026 ===
  {"date":"2026-03-12","artist":"Fit For A King","support":"Memphis May Fire, Acres, 156/Silence","city":"Cologne","country":"Germany","venue":"E-Werk","tour":"Lonely God European Tour 2026","ticketUrl":"https://lnk.to/FFAK-COLOGNE26"},
  {"date":"2026-03-13","artist":"Fit For A King","support":"Memphis May Fire, Acres, 156/Silence","city":"Wiesbaden","country":"Germany","venue":"Schlachthof","tour":"Lonely God European Tour 2026","ticketUrl":"https://lnk.to/FFAK-WIESBADEN26"},
  {"date":"2026-03-14","artist":"Fit For A King","support":"Memphis May Fire, Acres, 156/Silence","city":"Hamburg","country":"Germany","venue":"Große Freiheit 36","tour":"Lonely God European Tour 2026","ticketUrl":"","soldOut":true},
  {"date":"2026-03-16","artist":"Fit For A King","support":"Memphis May Fire, Acres, 156/Silence","city":"Antwerp","country":"Belgium","venue":"Trix","tour":"Lonely God European Tour 2026","ticketUrl":"https://lnk.to/FFAK-ANTWERP26"},
  {"date":"2026-03-17","artist":"Fit For A King","support":"Memphis May Fire, Acres, 156/Silence","city":"Tilburg","country":"Netherlands","venue":"0 1 3","tour":"Lonely God European Tour 2026","ticketUrl":"https://lnk.to/FFAK-TILBURG26"},
  {"date":"2026-03-19","artist":"Fit For A King","support":"Memphis May Fire, Acres, 156/Silence","city":"Manchester","country":"UK","venue":"O2 Ritz","tour":"Lonely God European Tour 2026","ticketUrl":"https://lnk.to/FFAK-MANCHESTER26"},
  {"date":"2026-03-20","artist":"Fit For A King","support":"Memphis May Fire, Acres, 156/Silence","city":"Leeds","country":"UK","venue":"Project House","tour":"Lonely God European Tour 2026","ticketUrl":"https://lnk.to/FFAK-LEEDS26"},
  {"date":"2026-03-22","artist":"Fit For A King","support":"Memphis May Fire, Acres, 156/Silence","city":"Nottingham","country":"UK","venue":"Rock City","tour":"Lonely God European Tour 2026","ticketUrl":"https://lnk.to/FFAK-NOTTINGHAM26"},
  {"date":"2026-03-23","artist":"Fit For A King","support":"Memphis May Fire, Acres, 156/Silence","city":"Bristol","country":"UK","venue":"Electric Bristol","tour":"Lonely God European Tour 2026","ticketUrl":"https://lnk.to/FFAK-BRISTOL26"},
  {"date":"2026-03-24","artist":"Fit For A King","support":"Memphis May Fire, Acres, 156/Silence","city":"London","country":"UK","venue":"Electric Ballroom","tour":"Lonely God European Tour 2026","ticketUrl":"https://lnk.to/FFAK-LONDON26"},
  {"date":"2026-03-26","artist":"Fit For A King","support":"Memphis May Fire, Acres, 156/Silence","city":"Paris","country":"France","venue":"Elysée Montmartre","tour":"Lonely God European Tour 2026","ticketUrl":"https://lnk.to/FFAK-PARIS26"},
  {"date":"2026-03-28","artist":"Fit For A King","support":"Memphis May Fire, Acres, 156/Silence","city":"Madrid","country":"Spain","venue":"Mon Live","tour":"Lonely God European Tour 2026","ticketUrl":"","soldOut":true},
  {"date":"2026-03-29","artist":"Fit For A King","support":"Memphis May Fire, Acres, 156/Silence","city":"Barcelona","country":"Spain","venue":"Razzmatazz 2","tour":"Lonely God European Tour 2026","ticketUrl":"https://lnk.to/FFAK-BARCELONA26"},
  {"date":"2026-03-30","artist":"Fit For A King","support":"Memphis May Fire, Acres, 156/Silence","city":"Lyon","country":"France","venue":"CCO La Rayonne","tour":"Lonely God European Tour 2026","ticketUrl":"https://lnk.to/FFAK-LYON26"},
  {"date":"2026-04-01","artist":"Fit For A King","support":"Memphis May Fire, Acres, 156/Silence","city":"Zurich","country":"Switzerland","venue":"Komplex 457","tour":"Lonely God European Tour 2026","ticketUrl":"https://lnk.to/FFAK-ZURICH26"},
  {"date":"2026-04-02","artist":"Fit For A King","support":"Memphis May Fire, Acres, 156/Silence","city":"Munich","country":"Germany","venue":"Tonhalle","tour":"Lonely God European Tour 2026","ticketUrl":"https://lnk.to/FFAK-MUNICH26"},
  {"date":"2026-04-03","artist":"Fit For A King","support":"Memphis May Fire, Acres, 156/Silence","city":"Linz","country":"Austria","venue":"Posthof","tour":"Lonely God European Tour 2026","ticketUrl":"https://lnk.to/FFAK-LINZ26"},
  {"date":"2026-04-04","artist":"Fit For A King","support":"Memphis May Fire, Acres, 156/Silence","city":"Leipzig","country":"Germany","venue":"Felsenkeller","tour":"Lonely God European Tour 2026","ticketUrl":"https://lnk.to/FFAK-LEIPZIG26"},
  {"date":"2026-04-06","artist":"Fit For A King","support":"Memphis May Fire, Acres, 156/Silence","city":"Prague","country":"Czech Republic","venue":"Roxy","tour":"Lonely God European Tour 2026","ticketUrl":"https://lnk.to/FFAK-PRAGUE26"},
  {"date":"2026-04-07","artist":"Fit For A King","support":"Memphis May Fire, Acres, 156/Silence","city":"Warsaw","country":"Poland","venue":"Progresja","tour":"Lonely God European Tour 2026","ticketUrl":"https://lnk.to/FFAK-WARSAW26"},
  {"date":"2026-04-08","artist":"Fit For A King","support":"Memphis May Fire, Acres, 156/Silence","city":"Berlin","country":"Germany","venue":"Huxleys","tour":"Lonely God European Tour 2026","ticketUrl":"https://lnk.to/FFAK-BERLIN26"},
  {"date":"2026-04-10","artist":"Fit For A King","support":"Memphis May Fire, Acres, 156/Silence","city":"Oslo","country":"Norway","venue":"Rockefeller","tour":"Lonely God European Tour 2026","ticketUrl":"https://lnk.to/FFAK-OSLO26"},
  {"date":"2026-04-11","artist":"Fit For A King","support":"Memphis May Fire, Acres, 156/Silence","city":"Stockholm","country":"Sweden","venue":"Fållan","tour":"Lonely God European Tour 2026","ticketUrl":"https://lnk.to/FFAK-STOCKHOLM26"},
  {"date":"2026-04-13","artist":"Fit For A King","support":"Memphis May Fire, Acres, 156/Silence","city":"Helsinki","country":"Finland","venue":"Kulttuuritalo","tour":"Lonely God European Tour 2026","ticketUrl":"https://lnk.to/FFAK-HELSINKI26"},

  // === THROWN - BALTICS & FINLAND TOUR 2026 ===
  {"date":"2026-04-07","artist":"Thrown","support":"Half Me","city":"Riga","country":"Latvia","venue":"","tour":"Baltics & Finland Tour 2026","ticketUrl":"https://lnk.to/thrown-riga"},
  {"date":"2026-04-08","artist":"Thrown","support":"Half Me","city":"Tallinn","country":"Estonia","venue":"","tour":"Baltics & Finland Tour 2026","ticketUrl":"https://lnk.to/thrown-tallinn"},
  {"date":"2026-04-10","artist":"Thrown","support":"Half Me","city":"Tampere","country":"Finland","venue":"","tour":"Baltics & Finland Tour 2026","ticketUrl":"https://lnk.to/thrown-tampere"},
  {"date":"2026-04-11","artist":"Thrown","support":"Half Me","city":"Helsinki","country":"Finland","venue":"","tour":"Baltics & Finland Tour 2026","ticketUrl":"https://lnk.to/thrown-helsinki"},

  // === MORNING AGAIN - EUROPE 2026 ===
  {"date":"2026-04-08","artist":"Morning Again","support":"","city":"Antwerp","country":"Belgium","venue":"Kavka","tour":"Europe 2026","ticketUrl":"https://lnk.to/MA-Antwerp26"},
  {"date":"2026-04-09","artist":"Morning Again","support":"","city":"Dordrecht","country":"Netherlands","venue":"Bibelot","tour":"Europe 2026","ticketUrl":"https://lnk.to/MA-Dordrecht26"},
  {"date":"2026-04-10","artist":"Morning Again","support":"","city":"Paris","country":"France","venue":"United We Stand Fest","tour":"Europe 2026","ticketUrl":"https://lnk.to/MA-Paris26"},
  {"date":"2026-04-11","artist":"Morning Again","support":"","city":"Moers","country":"Germany","venue":"Break Down The Walls","tour":"Europe 2026","ticketUrl":"https://lnk.to/MA-BDTW26"},
  {"date":"2026-04-12","artist":"Morning Again","support":"","city":"London","country":"UK","venue":"The Underworld","tour":"Europe 2026","ticketUrl":"https://lnk.to/MA-London26"},

  // === NEVER EASY - I STILL CARE TOUR 2026 ===
  {"date":"2026-04-23","artist":"Never Easy","support":"Love Is Noise, Newshapes","city":"Amsterdam","country":"Netherlands","venue":"Tolhuistuin","tour":"I STILL CARE TOUR 2026","ticketUrl":"https://lnk.to/NE-AMSTERDAM26"},
  {"date":"2026-04-24","artist":"Never Easy","support":"Love Is Noise, Newshapes","city":"Paris","country":"France","venue":"Maroquinerie","tour":"I STILL CARE TOUR 2026","ticketUrl":"https://lnk.to/NE-PARIS26"},
  {"date":"2026-04-27","artist":"Never Easy","support":"Love Is Noise, Newshapes","city":"Bristol","country":"UK","venue":"Exchange","tour":"I STILL CARE TOUR 2026","ticketUrl":"https://lnk.to/NE-BRISTOL26"},
  {"date":"2026-04-28","artist":"Never Easy","support":"Love Is Noise, Newshapes","city":"Leeds","country":"UK","venue":"Key Club","tour":"I STILL CARE TOUR 2026","ticketUrl":"https://lnk.to/NE-LEEDS26"},
  {"date":"2026-04-29","artist":"Never Easy","support":"Love Is Noise, Newshapes","city":"Glasgow","country":"UK","venue":"Classic Grand","tour":"I STILL CARE TOUR 2026","ticketUrl":"https://lnk.to/NE-GLASGOW26"},
  {"date":"2026-04-30","artist":"Never Easy","support":"Love Is Noise, Newshapes","city":"Manchester","country":"UK","venue":"Deaf Institute","tour":"I STILL CARE TOUR 2026","ticketUrl":"https://lnk.to/NE-MANCHESTER26"},
  {"date":"2026-05-01","artist":"Never Easy","support":"Love Is Noise, Newshapes","city":"Birmingham","country":"UK","venue":"Mama Roux","tour":"I STILL CARE TOUR 2026","ticketUrl":"https://lnk.to/NE-BIRMINGHAM26"},
  {"date":"2026-05-02","artist":"Never Easy","support":"Love Is Noise, Newshapes","city":"London","country":"UK","venue":"Oslo Hackney","tour":"I STILL CARE TOUR 2026","ticketUrl":"https://lnk.to/NE-LONDON26"},
  {"date":"2026-05-04","artist":"Never Easy","support":"Love Is Noise, Newshapes","city":"Hamburg","country":"Germany","venue":"Logo","tour":"I STILL CARE TOUR 2026","ticketUrl":"https://lnk.to/NE-HAMBURG26"},
  {"date":"2026-05-05","artist":"Never Easy","support":"Love Is Noise, Newshapes","city":"Wiesbaden","country":"Germany","venue":"Schlachthof","tour":"I STILL CARE TOUR 2026","ticketUrl":"https://lnk.to/NE-WIESBADEN26"},
  {"date":"2026-05-06","artist":"Never Easy","support":"Love Is Noise, Newshapes","city":"Munich","country":"Germany","venue":"Backstage","tour":"I STILL CARE TOUR 2026","ticketUrl":"https://lnk.to/NE-MUNICH26"},
  {"date":"2026-05-07","artist":"Never Easy","support":"Love Is Noise, Newshapes","city":"Prague","country":"Czech Republic","venue":"Bike Jesus","tour":"I STILL CARE TOUR 2026","ticketUrl":"https://lnk.to/NE-PRAGUE26"},
  {"date":"2026-05-08","artist":"Never Easy","support":"Love Is Noise, Newshapes","city":"Berlin","country":"Germany","venue":"Cassiopeia","tour":"I STILL CARE TOUR 2026","ticketUrl":"https://lnk.to/NE-BERLIN26"},
  {"date":"2026-05-09","artist":"Never Easy","support":"Love Is Noise, Newshapes","city":"Cologne","country":"Germany","venue":"MTC","tour":"I STILL CARE TOUR 2026","ticketUrl":"https://lnk.to/NE-COLOGNE26"},

  // === PALEDUSK - EU/UK TOUR 2026 ===
  {"date":"2026-05-07","artist":"Paledusk","support":"Greyhaven, Headwreck","city":"Bristol","country":"UK","venue":"The Fleece","tour":"EU/UK Tour 2026","ticketUrl":"http://lnk.to/PD2026-Bristol"},
  {"date":"2026-05-08","artist":"Paledusk","support":"Greyhaven, Headwreck","city":"Manchester","country":"UK","venue":"Academy 3","tour":"EU/UK Tour 2026","ticketUrl":"http://lnk.to/PD2026-Manchester"},
  {"date":"2026-05-09","artist":"Paledusk","support":"Greyhaven, Headwreck","city":"London","country":"UK","venue":"The Dome","tour":"EU/UK Tour 2026","ticketUrl":"http://lnk.to/PD2026-London"},
  {"date":"2026-05-11","artist":"Paledusk","support":"Greyhaven, Headwreck","city":"Paris","country":"France","venue":"Backstage By The Mill","tour":"EU/UK Tour 2026","ticketUrl":"http://lnk.to/PD2026-Paris"},
  {"date":"2026-05-12","artist":"Paledusk","support":"Greyhaven, Headwreck","city":"Toulouse","country":"France","venue":"Le Rex","tour":"EU/UK Tour 2026","ticketUrl":"http://lnk.to/PD2026-Toulouse"},
  {"date":"2026-05-13","artist":"Paledusk","support":"Greyhaven, Headwreck","city":"Barcelona","country":"Spain","venue":"Razzmatazz 2","tour":"EU/UK Tour 2026","ticketUrl":"http://lnk.to/PD2026-Barcelona"},
  {"date":"2026-05-14","artist":"Paledusk","support":"Greyhaven, Headwreck","city":"Madrid","country":"Spain","venue":"ReviLive","tour":"EU/UK Tour 2026","ticketUrl":"http://lnk.to/PD2026-Madrid"},
  {"date":"2026-05-16","artist":"Paledusk","support":"Greyhaven, Headwreck","city":"Lyon","country":"France","venue":"Marché Gare","tour":"EU/UK Tour 2026","ticketUrl":"http://lnk.to/PD2026-Lyon"},
  {"date":"2026-05-17","artist":"Paledusk","support":"Greyhaven, Headwreck","city":"Milan","country":"Italy","venue":"Magazzini Generali","tour":"EU/UK Tour 2026","ticketUrl":"http://lnk.to/PD2026-Milan"},
  {"date":"2026-05-18","artist":"Paledusk","support":"Greyhaven, Headwreck","city":"Munich","country":"Germany","venue":"Feierwerk","tour":"EU/UK Tour 2026","ticketUrl":"http://lnk.to/PD2026-Munich"},
  {"date":"2026-05-19","artist":"Paledusk","support":"Greyhaven, Headwreck","city":"Vienna","country":"Austria","venue":"Viper Room","tour":"EU/UK Tour 2026","ticketUrl":"http://lnk.to/PD2026-Vienna"},
  {"date":"2026-05-21","artist":"Paledusk","support":"Greyhaven, Headwreck","city":"Prague","country":"Czech Republic","venue":"Cargo Gallery","tour":"EU/UK Tour 2026","ticketUrl":"http://lnk.to/PD2026-Prague"},
  {"date":"2026-05-22","artist":"Paledusk","support":"Greyhaven, Headwreck","city":"Berlin","country":"Germany","venue":"Lido","tour":"EU/UK Tour 2026","ticketUrl":"http://lnk.to/PD2026-Berlin"},
  {"date":"2026-05-23","artist":"Paledusk","support":"Greyhaven, Headwreck","city":"Cologne","country":"Germany","venue":"Gebäude 9","tour":"EU/UK Tour 2026","ticketUrl":"http://lnk.to/PD2026-Cologne","soldOut":true},
  {"date":"2026-05-24","artist":"Paledusk","support":"Greyhaven, Headwreck","city":"Hamburg","country":"Germany","venue":"Logo","tour":"EU/UK Tour 2026","ticketUrl":"http://lnk.to/PD2026-Hamburg"},
  {"date":"2026-05-26","artist":"Paledusk","support":"Greyhaven, Headwreck","city":"Utrecht","country":"Netherlands","venue":"De Helling","tour":"EU/UK Tour 2026","ticketUrl":"http://lnk.to/PD2026-Utrecht"},
  {"date":"2026-05-27","artist":"Paledusk","support":"Greyhaven, Headwreck","city":"Antwerp","country":"Belgium","venue":"Kavka Zappa","tour":"EU/UK Tour 2026","ticketUrl":"http://lnk.to/PD2026-Antwerp"},

  // === HANDS LIKE HOUSES & BROADSIDE - EUROPEAN CO-HEADLINE TOUR 2026 ===
  {"date":"2026-05-11","artist":"Hands Like Houses & Broadside","support":"","city":"Prague","country":"Czech Republic","venue":"Bike Jesus","tour":"EUROPEAN CO-HEADLINE TOUR 2026","ticketUrl":"http://lnk.to/HLH-Broadside-Prague"},
  {"date":"2026-05-12","artist":"Hands Like Houses & Broadside","support":"","city":"Vienna","country":"Austria","venue":"Flex Café","tour":"EUROPEAN CO-HEADLINE TOUR 2026","ticketUrl":"http://lnk.to/HLH-Broadside-Vienna"},
  {"date":"2026-05-13","artist":"Hands Like Houses & Broadside","support":"","city":"Budapest","country":"Hungary","venue":"Dürer Kert","tour":"EUROPEAN CO-HEADLINE TOUR 2026","ticketUrl":"http://lnk.to/HLH-Broadside-Budapest"},
  {"date":"2026-05-15","artist":"Hands Like Houses & Broadside","support":"","city":"Dischingen","country":"Germany","venue":"Heavydays Festival","tour":"EUROPEAN CO-HEADLINE TOUR 2026","ticketUrl":"https://heavydays.de/"},
  {"date":"2026-05-16","artist":"Hands Like Houses & Broadside","support":"","city":"Schweinfurt","country":"Germany","venue":"Stattbahnhof","tour":"EUROPEAN CO-HEADLINE TOUR 2026","ticketUrl":"http://lnk.to/HLH-Broadside-Schweinfurt"},
  {"date":"2026-05-17","artist":"Hands Like Houses & Broadside","support":"","city":"Hamburg","country":"Germany","venue":"Betty","tour":"EUROPEAN CO-HEADLINE TOUR 2026","ticketUrl":"http://lnk.to/HLH-Broadside-Hamburg"},
  {"date":"2026-05-19","artist":"Hands Like Houses & Broadside","support":"","city":"Cologne","country":"Germany","venue":"MTC","tour":"EUROPEAN CO-HEADLINE TOUR 2026","ticketUrl":"http://lnk.to/HLH-Cologne"},
  {"date":"2026-05-20","artist":"Hands Like Houses & Broadside","support":"","city":"Tilburg","country":"Netherlands","venue":"Hall Of Fame","tour":"EUROPEAN CO-HEADLINE TOUR 2026","ticketUrl":"http://lnk.to/HLH-Broadside-Tilburg"},
  {"date":"2026-05-21","artist":"Hands Like Houses & Broadside","support":"","city":"Paris","country":"France","venue":"Backstage By The Mill","tour":"EUROPEAN CO-HEADLINE TOUR 2026","ticketUrl":"http://lnk.to/HLH-Broadside-Paris"},
  {"date":"2026-05-23","artist":"Hands Like Houses & Broadside","support":"","city":"Hatfield","country":"UK","venue":"Slam Dunk South","tour":"EUROPEAN CO-HEADLINE TOUR 2026","ticketUrl":"https://www.slamdunkfestival.com/"},
  {"date":"2026-05-24","artist":"Hands Like Houses & Broadside","support":"","city":"Leeds","country":"UK","venue":"Slam Dunk North","tour":"EUROPEAN CO-HEADLINE TOUR 2026","ticketUrl":"https://www.slamdunkfestival.com/"},

  // === KUBLAI KHAN TX - EUROPE SUMMER 2026 ===
  {"date":"2026-06-03","artist":"Kublai Khan TX","support":"","city":"Gdansk","country":"Poland","venue":"Mystic Festival","tour":"Europe Summer 2026","ticketUrl":"https://www.mysticfestival.pl/"},
  {"date":"2026-06-05","artist":"Kublai Khan TX","support":"Boundaries","city":"Berlin","country":"Germany","venue":"Hole44","tour":"Europe Summer 2026","ticketUrl":"https://lnk.to/KKTX-BERLIN26"},
  {"date":"2026-06-06","artist":"Kublai Khan TX","support":"","city":"Nuremberg","country":"Germany","venue":"Rock Im Park","tour":"Europe Summer 2026","ticketUrl":"https://www.rock-im-park.com/"},
  {"date":"2026-06-07","artist":"Kublai Khan TX","support":"","city":"Nurburgring","country":"Germany","venue":"Rock Am Ring","tour":"Europe Summer 2026","ticketUrl":"https://www.rock-am-ring.com/"},
  {"date":"2026-06-08","artist":"Kublai Khan TX","support":"Malevolence, Dying Wish","city":"Venice","country":"Italy","venue":"Revolver","tour":"Europe Summer 2026","ticketUrl":"https://lnk.to/KKTX-VENICE26"},
  {"date":"2026-06-09","artist":"Kublai Khan TX","support":"Malevolence, Boundaries","city":"Ljubljana","country":"Slovenia","venue":"Kino Šiška","tour":"Europe Summer 2026","ticketUrl":"https://lnk.to/KKTX-LJUBLJANA26"},
  {"date":"2026-06-10","artist":"Kublai Khan TX","support":"","city":"Hradec Kralove","country":"Czech Republic","venue":"Rock For People","tour":"Europe Summer 2026","ticketUrl":"https://rockforpeople.cz/en/"},
  {"date":"2026-06-12","artist":"Kublai Khan TX","support":"","city":"Torgau","country":"Germany","venue":"Aint Like You","tour":"Europe Summer 2026","ticketUrl":"https://aintlikeyoufestival.de/"},
  {"date":"2026-06-13","artist":"Kublai Khan TX","support":"","city":"Nickelsdorf","country":"Austria","venue":"Nova Rock","tour":"Europe Summer 2026","ticketUrl":"https://www.novarock.at/"},
  {"date":"2026-06-14","artist":"Kublai Khan TX","support":"","city":"Donington","country":"UK","venue":"Download","tour":"Europe Summer 2026","ticketUrl":"https://downloadfestival.co.uk/"},
  {"date":"2026-06-15","artist":"Kublai Khan TX","support":"Heriot","city":"Dublin","country":"Ireland","venue":"Opium","tour":"Europe Summer 2026","ticketUrl":"https://lnk.to/KKTX-DUBLIN26"},
  {"date":"2026-06-16","artist":"Kublai Khan TX","support":"","city":"Belfast","country":"N. Ireland","venue":"Limelight 2","tour":"Europe Summer 2026","ticketUrl":"https://lnk.to/KKTX-BELFAST26"},
  {"date":"2026-06-17","artist":"Kublai Khan TX","support":"Boundaries","city":"Cardiff","country":"UK","venue":"Y Plas","tour":"Europe Summer 2026","ticketUrl":"https://lnk.to/KKTX-CARDIFF26"},
  {"date":"2026-06-19","artist":"Kublai Khan TX","support":"","city":"Dessel","country":"Belgium","venue":"Graspop","tour":"Europe Summer 2026","ticketUrl":"https://www.graspop.be/en/"},
  {"date":"2026-06-20","artist":"Kublai Khan TX","support":"","city":"Clisson","country":"France","venue":"Hellfest","tour":"Europe Summer 2026","ticketUrl":"https://hellfest.fr/en"},
  {"date":"2026-06-22","artist":"Kublai Khan TX","support":"Shai Hulud, Denial of Life, Volatile Ways","city":"Amsterdam","country":"Netherlands","venue":"Melkweg","tour":"Europe Summer 2026","ticketUrl":"https://lnk.to/KKTX-AMSTERDAM26"},
  {"date":"2026-06-24","artist":"Kublai Khan TX","support":"","city":"Stockholm","country":"Sweden","venue":"Broken Summer","tour":"Europe Summer 2026","ticketUrl":"https://www.brokensummer.se/"},
  {"date":"2026-06-25","artist":"Kublai Khan TX","support":"","city":"Copenhagen","country":"Denmark","venue":"Copenhell","tour":"Europe Summer 2026","ticketUrl":"https://copenhell.dk/"},
  {"date":"2026-06-26","artist":"Kublai Khan TX","support":"","city":"Oslo","country":"Norway","venue":"Tons Of Rock","tour":"Europe Summer 2026","ticketUrl":"https://www.tonsofrock.no/"},
  {"date":"2026-06-27","artist":"Kublai Khan TX","support":"","city":"Helsinki","country":"Finland","venue":"Tuska","tour":"Europe Summer 2026","ticketUrl":"https://tuska.fi/en/"},

  // === EXCIDE - UK SUMMER 2026 ===
  {"date":"2026-06-04","artist":"Excide","support":"Hollow Sun","city":"Leeds","country":"UK","venue":"Key Club","tour":"UK Summer 2026","ticketUrl":"https://lnk.to/EXCIDE-LEEDS26"},
  {"date":"2026-06-05","artist":"Excide","support":"Hollow Sun","city":"Manchester","country":"UK","venue":"The Lodge","tour":"UK Summer 2026","ticketUrl":"https://lnk.to/EXCIDE-MANCHESTER26"},
  {"date":"2026-06-06","artist":"Excide","support":"Hollow Sun","city":"Glasgow","country":"UK","venue":"Nice n ' Sleazy","tour":"UK Summer 2026","ticketUrl":"https://lnk.to/EXCIDE-GLASGOW26"},
  {"date":"2026-06-07","artist":"Excide","support":"Hollow Sun","city":"Birmingham","country":"UK","venue":"The Flapper","tour":"UK Summer 2026","ticketUrl":"https://lnk.to/EXCIDE-BIRMINGHAM26"},
  {"date":"2026-06-08","artist":"Excide","support":"Hollow Sun","city":"London","country":"UK","venue":"New Cross Inn","tour":"UK Summer 2026","ticketUrl":"https://lnk.to/EXCIDE-LONDON26"},

  // === THE PLOT IN YOU - EUROPE 2026 ===
  {"date":"2026-06-05","artist":"The Plot In You","support":"","city":"Nurburgring","country":"Germany","venue":"Rock Am Ring","tour":"Europe 2026","ticketUrl":"https://www.rock-am-ring.com/"},
  {"date":"2026-06-07","artist":"The Plot In You","support":"","city":"Nuremberg","country":"Germany","venue":"Rock Im Park","tour":"Europe 2026","ticketUrl":"https://www.rock-im-park.com/"},
  {"date":"2026-06-09","artist":"The Plot In You","support":"Silent Planet","city":"Milan","country":"Italy","venue":"Alcatraz","tour":"Europe 2026","ticketUrl":"https://lnk.to/TPIY-MILAN2026"},
  {"date":"2026-06-10","artist":"The Plot In You","support":"Silent Planet","city":"Innsbruck","country":"Austria","venue":"Music Hall","tour":"Europe 2026","ticketUrl":"https://lnk.to/TPIY-INNSBRUCK2026"},
  {"date":"2026-06-11","artist":"The Plot In You","support":"","city":"Hradec Kralove","country":"Czech Republic","venue":"Rock For People","tour":"Europe 2026","ticketUrl":"https://rockforpeople.cz/en/"},
  {"date":"2026-06-12","artist":"The Plot In You","support":"","city":"Nickelsdorf","country":"Austria","venue":"Nova Rock","tour":"Europe 2026","ticketUrl":"https://www.novarock.at/"},
  {"date":"2026-06-14","artist":"The Plot In You","support":"","city":"Donington","country":"UK","venue":"Download","tour":"Europe 2026","ticketUrl":"https://downloadfestival.co.uk/"},
  {"date":"2026-06-15","artist":"The Plot In You","support":"Boundaries","city":"Belfast","country":"Ireland","venue":"The Limelight","tour":"Europe 2026","ticketUrl":"https://lnk.to/TPIY-BELFAST2026"},
  {"date":"2026-06-16","artist":"The Plot In You","support":"Boundaries","city":"Dublin","country":"Ireland","venue":"Academy","tour":"Europe 2026","ticketUrl":"https://lnk.to/TPIY-DUBLIN2026"},
  {"date":"2026-06-18","artist":"The Plot In You","support":"","city":"Clisson","country":"France","venue":"Hellfest","tour":"Europe 2026","ticketUrl":"https://hellfest.fr/en"},
  {"date":"2026-06-19","artist":"The Plot In You","support":"","city":"Landgraaf","country":"Netherlands","venue":"Pinkpop","tour":"Europe 2026","ticketUrl":"https://www.pinkpop.nl/"},
  {"date":"2026-06-21","artist":"The Plot In You","support":"","city":"Dessel","country":"Belgium","venue":"Graspop","tour":"Europe 2026","ticketUrl":"https://www.graspop.be/en/"},
  {"date":"2026-06-22","artist":"The Plot In You","support":"Boundaries, Rain City Drive","city":"Bremen","country":"Germany","venue":"Aladin","tour":"Europe 2026","ticketUrl":"https://lnk.to/TPIY-BREMEN2026"},
  {"date":"2026-06-24","artist":"The Plot In You","support":"","city":"Stockholm","country":"Sweden","venue":"Broken Summer","tour":"Europe 2026","ticketUrl":"https://www.brokensummer.se/"},
  {"date":"2026-06-27","artist":"The Plot In You","support":"","city":"Helsinki","country":"Finland","venue":"Tuska","tour":"Europe 2026","ticketUrl":"https://tuska.fi/en/"},

  // === SILENT PLANET - EU/UK SUMMER 2026 ===
  {"date":"2026-06-07","artist":"Silent Planet","support":"","city":"Graz","country":"Austria","venue":"Core & More Festival","tour":"EU/UK Summer 2026","ticketUrl":"https://spielstaetten.buehnen-graz.com/coreandmore/"},
  {"date":"2026-06-09","artist":"Silent Planet","support":"","city":"Milan","country":"Italy","venue":"Alcatraz","tour":"EU/UK Summer 2026","ticketUrl":"https://lnk.to/TPIY-MILAN2026"},
  {"date":"2026-06-10","artist":"Silent Planet","support":"","city":"Innsbruck","country":"Austria","venue":"Music Hall","tour":"EU/UK Summer 2026","ticketUrl":"https://lnk.to/TPIY-INNSBRUCK2026"},
  {"date":"2026-06-12","artist":"Silent Planet","support":"","city":"Donington","country":"UK","venue":"Download","tour":"EU/UK Summer 2026","ticketUrl":"https://downloadfestival.co.uk/"},
  {"date":"2026-06-13","artist":"Silent Planet","support":"","city":"Hradec Kralove","country":"Czech Republic","venue":"Rock For People","tour":"EU/UK Summer 2026","ticketUrl":"https://rockforpeople.cz/en/"},
  {"date":"2026-06-15","artist":"Silent Planet","support":"","city":"Nuremberg","country":"Germany","venue":"Z-Bau","tour":"EU/UK Summer 2026","ticketUrl":"https://lnk.to/SP-RCD-NUREMBERG26"},
  {"date":"2026-06-16","artist":"Silent Planet","support":"","city":"Hannover","country":"Germany","venue":"Faust","tour":"EU/UK Summer 2026","ticketUrl":"https://lnk.to/SP-RCD-HANNOVER26"},
  {"date":"2026-06-18","artist":"Silent Planet","support":"","city":"Warsaw","country":"Poland","venue":"Summer Punch Festival","tour":"EU/UK Summer 2026","ticketUrl":"https://www.summerpunchfestival.com/"},
  {"date":"2026-06-20","artist":"Silent Planet","support":"","city":"Kyiv","country":"Ukraine","venue":"Atlas Club","tour":"EU/UK Summer 2026","ticketUrl":"https://lnk.to/SP-KYIV26"},
  {"date":"2026-06-21","artist":"Silent Planet","support":"","city":"Lviv","country":"Ukraine","venue":"Festrepublic Club","tour":"EU/UK Summer 2026","ticketUrl":"https://lnk.to/SP-LVIV26"},

  // === QUEENSRŸCHE - EUROPE SUMMER 2026 ===
  {"date":"2026-06-12","artist":"Queensrÿche","support":"Rivers Of Nihil","city":"Cologne","country":"Germany","venue":"Essigfabrik","tour":"Europe Summer 2026","ticketUrl":"https://lnk.to/QR-COLOGNE26"},
  {"date":"2026-06-13","artist":"Queensrÿche","support":"Rivers Of Nihil (selected dates)","city":"Leeuwarden","country":"Netherlands","venue":"Into The Grave","tour":"Europe Summer 2026","ticketUrl":"https://intothegrave.nl/"},
  {"date":"2026-06-14","artist":"Queensrÿche","support":"Rivers Of Nihil (selected dates)","city":"Hradec Kralove","country":"Czech Republic","venue":"Rock For People","tour":"Europe Summer 2026","ticketUrl":"https://rockforpeople.cz/en/"},
  {"date":"2026-06-16","artist":"Queensrÿche","support":"Rivers Of Nihil","city":"Hamburg","country":"Germany","venue":"Markthalle","tour":"Europe Summer 2026","ticketUrl":"https://lnk.to/QR-HAMBURG26"},
  {"date":"2026-06-17","artist":"Queensrÿche","support":"Rivers Of Nihil","city":"Frankfurt","country":"Germany","venue":"Batschkapp","tour":"Europe Summer 2026","ticketUrl":"https://lnk.to/QR-FRANKFURT26"},
  {"date":"2026-06-19","artist":"Queensrÿche","support":"Rivers Of Nihil (selected dates)","city":"Clisson","country":"France","venue":"Hellfest","tour":"Europe Summer 2026","ticketUrl":"https://hellfest.fr/en"},
  {"date":"2026-06-20","artist":"Queensrÿche","support":"Rivers Of Nihil (selected dates)","city":"Dessel","country":"Belgium","venue":"Graspop","tour":"Europe Summer 2026","ticketUrl":"https://www.graspop.be/en/"},
  {"date":"2026-06-22","artist":"Queensrÿche","support":"Rivers Of Nihil","city":"Manchester","country":"UK","venue":"Club Academy","tour":"Europe Summer 2026","ticketUrl":"https://lnk.to/QR-MANCHESTER26"},
  {"date":"2026-06-23","artist":"Queensrÿche","support":"Rivers Of Nihil","city":"London","country":"UK","venue":"Islington Assembly Hall","tour":"Europe Summer 2026","ticketUrl":"https://lnk.to/QR-LONDON26"},
  {"date":"2026-06-25","artist":"Queensrÿche","support":"Rivers Of Nihil (selected dates)","city":"Copenhagen","country":"Denmark","venue":"Copenhell","tour":"Europe Summer 2026","ticketUrl":"https://copenhell.dk/"},
  {"date":"2026-06-26","artist":"Queensrÿche","support":"Rivers Of Nihil (selected dates)","city":"Oslo","country":"Norway","venue":"Tons Of Rock","tour":"Europe Summer 2026","ticketUrl":"https://www.tonsofrock.no/"},
  {"date":"2026-06-28","artist":"Queensrÿche","support":"Rivers Of Nihil (selected dates)","city":"Helsinki","country":"Finland","venue":"Tuska","tour":"Europe Summer 2026","ticketUrl":"https://tuska.fi/en/"},
  {"date":"2026-06-30","artist":"Queensrÿche","support":"Rivers Of Nihil","city":"Lund","country":"Sweden","venue":"Mejeriet SE","tour":"Europe Summer 2026","ticketUrl":"https://lnk.to/QR-LUND26"},
  {"date":"2026-07-01","artist":"Queensrÿche","support":"Rivers Of Nihil","city":"Hannover","country":"Germany","venue":"Pavillon","tour":"Europe Summer 2026","ticketUrl":"https://lnk.to/QR-HANNOVER26"},
  {"date":"2026-07-02","artist":"Queensrÿche","support":"Rivers Of Nihil","city":"Lindau","country":"Germany","venue":"Club Vaudeville","tour":"Europe Summer 2026","ticketUrl":"https://lnk.to/QR-LINDAU26"},
  {"date":"2026-07-03","artist":"Queensrÿche","support":"Rivers Of Nihil (selected dates)","city":"Colombier-Saugnieu","country":"France","venue":"Plane’R Fest","tour":"Europe Summer 2026","ticketUrl":"https://planerfest.com/en/"},
  {"date":"2026-07-05","artist":"Queensrÿche","support":"Rivers Of Nihil (selected dates)","city":"Cartagena","country":"Spain","venue":"Rock Imperium Festival","tour":"Europe Summer 2026","ticketUrl":"https://www.rockimperiumfestival.es/en/"},

  // === RAIN CITY DRIVE - EUROPE SUMMER 2026 ===
  {"date":"2026-06-12","artist":"Rain City Drive","support":"","city":"Donington","country":"UK","venue":"Download","tour":"Europe Summer 2026","ticketUrl":"https://downloadfestival.co.uk/"},
  {"date":"2026-06-14","artist":"Rain City Drive","support":"","city":"Hradec Kralove","country":"Czech Republic","venue":"Rock For People","tour":"Europe Summer 2026","ticketUrl":"https://rockforpeople.cz/en/"},
  {"date":"2026-06-15","artist":"Rain City Drive","support":"Silent Planet","city":"Nuremberg","country":"Germany","venue":"Z-Bau","tour":"Europe Summer 2026","ticketUrl":"https://lnk.to/SP-RCD-NUREMBERG26"},
  {"date":"2026-06-16","artist":"Rain City Drive","support":"Silent Planet","city":"Hannover","country":"Germany","venue":"Faust","tour":"Europe Summer 2026","ticketUrl":"https://lnk.to/SP-RCD-HANNOVER26"},
  {"date":"2026-06-18","artist":"Rain City Drive","support":"","city":"Warsaw","country":"Poland","venue":"Summer Punch","tour":"Europe Summer 2026","ticketUrl":"https://www.summerpunchfestival.com/"},
  {"date":"2026-06-19","artist":"Rain City Drive","support":"Bury Tomorrow","city":"Jena","country":"Germany","venue":"F-Haus","tour":"Europe Summer 2026","ticketUrl":"https://www.eventim.de/event/bury-tomorrow-f-haus-21019954/"},
  {"date":"2026-06-21","artist":"Rain City Drive","support":"","city":"Dessel","country":"Belgium","venue":"Graspop","tour":"Europe Summer 2026","ticketUrl":"https://www.graspop.be/en/"},
  {"date":"2026-06-22","artist":"Rain City Drive","support":"The Plot In You","city":"Bremen","country":"Germany","venue":"Aladin","tour":"Europe Summer 2026","ticketUrl":"https://lnk.to/TPIY-BREMEN2026"},
  {"date":"2026-06-23","artist":"Rain City Drive","support":"Periphery","city":"Cologne","country":"Germany","venue":"Live Music Hall","tour":"Europe Summer 2026","ticketUrl":"https://www.eventim.de/event/periphery-live-music-hall-21343099/"},
  {"date":"2026-06-24","artist":"Rain City Drive","support":"Periphery","city":"Hamburg","country":"Germany","venue":"Markthalle","tour":"Europe Summer 2026","ticketUrl":"https://www.eventim.de/event/periphery-markthalle-hamburg-21348854/"},
  {"date":"2026-06-26","artist":"Rain City Drive","support":"Lifespark","city":"Karlsruhe","country":"Germany","venue":"Die Stadtmitte","tour":"Europe Summer 2026","ticketUrl":"https://lnk.to/RCD-KARLSRUHE26"},
  {"date":"2026-06-27","artist":"Rain City Drive","support":"","city":"Ysselsteyn","country":"Netherlands","venue":"Jera On Air","tour":"Europe Summer 2026","ticketUrl":"https://www.jeraonair.nl/en/"},

  // === RIVERS OF NIHIL - EUROPE SUMMER 2026 ===
  {"date":"2026-06-12","artist":"Rivers Of Nihil","support":"Queensryche","city":"Cologne","country":"Germany","venue":"Essigfabrik","tour":"Europe Summer 2026","ticketUrl":"https://lnk.to/QR-COLOGNE26"},
  {"date":"2026-06-13","artist":"Rivers Of Nihil","support":"","city":"Vechta","country":"Germany","venue":"Gulfhaus","tour":"Europe Summer 2026","ticketUrl":"https://lnk.to/RON-VECHTA26"},
  {"date":"2026-06-14","artist":"Rivers Of Nihil","support":"","city":"Leeuwarden","country":"Netherlands","venue":"Into The Grave","tour":"Europe Summer 2026","ticketUrl":"https://intothegrave.nl/"},
  {"date":"2026-06-16","artist":"Rivers Of Nihil","support":"Queensryche","city":"Hamburg","country":"Germany","venue":"Markthalle","tour":"Europe Summer 2026","ticketUrl":"https://lnk.to/QR-HAMBURG26"},
  {"date":"2026-06-17","artist":"Rivers Of Nihil","support":"Queensryche","city":"Frankfurt","country":"Germany","venue":"Batschkapp","tour":"Europe Summer 2026","ticketUrl":"https://lnk.to/QR-FRANKFURT26"},
  {"date":"2026-06-18","artist":"Rivers Of Nihil","support":"","city":"Clisson","country":"France","venue":"Hellfest","tour":"Europe Summer 2026","ticketUrl":"https://hellfest.fr/en"},
  {"date":"2026-06-20","artist":"Rivers Of Nihil","support":"","city":"Dessel","country":"Belgium","venue":"Graspop","tour":"Europe Summer 2026","ticketUrl":"https://www.graspop.be/en/"},
  {"date":"2026-06-22","artist":"Rivers Of Nihil","support":"Queensryche","city":"Manchester","country":"UK","venue":"Club Academy","tour":"Europe Summer 2026","ticketUrl":"https://lnk.to/QR-MANCHESTER26"},
  {"date":"2026-06-23","artist":"Rivers Of Nihil","support":"Queensryche","city":"London","country":"UK","venue":"Islington Assembly Hall","tour":"Europe Summer 2026","ticketUrl":"https://lnk.to/QR-LONDON26"},
  {"date":"2026-06-25","artist":"Rivers Of Nihil","support":"","city":"Warsaw","country":"Poland","venue":"Hybrydy","tour":"Europe Summer 2026","ticketUrl":"https://lnk.to/RON-WARSAW26"},
  {"date":"2026-06-26","artist":"Rivers Of Nihil","support":"","city":"Riga","country":"Latvia","venue":"Melna Piektdiena","tour":"Europe Summer 2026","ticketUrl":"https://lnk.to/RON-RIGA26"},
  {"date":"2026-06-27","artist":"Rivers Of Nihil","support":"","city":"Helsinki","country":"Finland","venue":"Tuska","tour":"Europe Summer 2026","ticketUrl":"https://tuska.fi/en/"},
  {"date":"2026-06-29","artist":"Rivers Of Nihil","support":"","city":"Gothenburg","country":"Sweden","venue":"Monument","tour":"Europe Summer 2026","ticketUrl":"https://lnk.to/RON-GOTHENBURG26"},
  {"date":"2026-06-30","artist":"Rivers Of Nihil","support":"Queensryche","city":"Lund","country":"Sweden","venue":"Mejeriet SE","tour":"Europe Summer 2026","ticketUrl":"https://lnk.to/QR-LUND26"},
  {"date":"2026-07-01","artist":"Rivers Of Nihil","support":"Queensryche","city":"Hannover","country":"Germany","venue":"Pavillon","tour":"Europe Summer 2026","ticketUrl":"https://lnk.to/QR-HANNOVER26"},
  {"date":"2026-07-02","artist":"Rivers Of Nihil","support":"Queensryche","city":"Lindau","country":"Germany","venue":"Club Vaudeville","tour":"Europe Summer 2026","ticketUrl":"https://lnk.to/QR-LINDAU26"},

  // === MAN WITH A MISSION - ‘MARKING NEW GROUND’ EUROPE SUMMER 2026 ===
  {"date":"2026-06-14","artist":"Man With A Mission","support":"","city":"Hradec Kralove","country":"Czech Republic","venue":"Rock For People","tour":"‘MARKING NEW GROUND’ EUROPE SUMMER 2026","ticketUrl":"https://rockforpeople.cz/en/"},
  {"date":"2026-06-17","artist":"Man With A Mission","support":"","city":"Budapest","country":"Hungary","venue":"Akvarium","tour":"‘MARKING NEW GROUND’ EUROPE SUMMER 2026","ticketUrl":"http://lnk.to/MWAM2026-Budapest"},
  {"date":"2026-06-19","artist":"Man With A Mission","support":"","city":"Warsaw","country":"Poland","venue":"Summer Punch","tour":"‘MARKING NEW GROUND’ EUROPE SUMMER 2026","ticketUrl":"https://summerpunchfestival.com/"},
  {"date":"2026-06-20","artist":"Man With A Mission","support":"","city":"Dresden","country":"Germany","venue":"Blauer Salon","tour":"‘MARKING NEW GROUND’ EUROPE SUMMER 2026","ticketUrl":"http://lnk.to/MWAM2026-Dresden"},
  {"date":"2026-06-23","artist":"Man With A Mission","support":"","city":"Stuttgart","country":"Germany","venue":"Im Wizemann","tour":"‘MARKING NEW GROUND’ EUROPE SUMMER 2026","ticketUrl":"http://lnk.to/MWAM2026-Stuttgart"},
  {"date":"2026-06-25","artist":"Man With A Mission","support":"","city":"Aarau","country":"Switzerland","venue":"KiFF","tour":"‘MARKING NEW GROUND’ EUROPE SUMMER 2026","ticketUrl":"http://lnk.to/MWAM2026-Aarau"},
  {"date":"2026-06-27","artist":"Man With A Mission","support":"","city":"Milan","country":"Italy","venue":"Asia Wave Fest","tour":"‘MARKING NEW GROUND’ EUROPE SUMMER 2026","ticketUrl":"http://lnk.to/ASIAWAVEFEST"},
  {"date":"2026-06-28","artist":"Man With A Mission","support":"","city":"Monthey","country":"Switzerland","venue":"Pont Rouge","tour":"‘MARKING NEW GROUND’ EUROPE SUMMER 2026","ticketUrl":"http://lnk.to/MWAM2026-Monthey"},
  {"date":"2026-07-01","artist":"Man With A Mission","support":"","city":"Viveiro","country":"Spain","venue":"Resurrection Fest","tour":"‘MARKING NEW GROUND’ EUROPE SUMMER 2026","ticketUrl":"https://www.resurrectionfest.es/"},

  // === SHAI HULUD - EUROPE SUMMER 2026 ===
  {"date":"2026-06-18","artist":"Shai Hulud","support":"","city":"Milan","country":"Italy","venue":"Q Club","tour":"EUROPE SUMMER 2026","ticketUrl":"https://lnk.to/SH-MILAN26"},
  {"date":"2026-06-20","artist":"Shai Hulud","support":"","city":"Querfurt","country":"Germany","venue":"Return to Strength","tour":"EUROPE SUMMER 2026","ticketUrl":"https://www.tixforgigs.com/Event/67171"},
  {"date":"2026-06-21","artist":"Shai Hulud","support":"","city":"Wiesbaden","country":"Germany","venue":"Schlachthof","tour":"EUROPE SUMMER 2026","ticketUrl":"https://lnk.to/SH-WIESBADEN26"},
  {"date":"2026-06-22","artist":"Shai Hulud","support":"","city":"Amsterdam","country":"Netherlands","venue":"Melkwe","tour":"EUROPE SUMMER 2026","ticketUrl":"https://lnk.to/KKTX-AMSTERDAM26"},
  {"date":"2026-07-02","artist":"Shai Hulud","support":"","city":"Neunkirchen","country":"Germany","venue":"Stummsche Reithalle","tour":"EUROPE SUMMER 2026","ticketUrl":"https://lnk.to/SH-NEUNKIRCHEN26"},
  {"date":"2026-07-03","artist":"Shai Hulud","support":"","city":"Tours","country":"France","venue":"RIIP Fest","tour":"EUROPE SUMMER 2026","ticketUrl":"https://www.helloasso.com/associations/riipost-association/evenements/riipfest-x"},
  {"date":"2026-07-04","artist":"Shai Hulud","support":"","city":"Ypres","country":"Belgium","venue":"Ieper Fest","tour":"EUROPE SUMMER 2026","ticketUrl":"https://shop.ticket.monster/event/ieperfest-2026-4ykvwm"},
  {"date":"2026-07-05","artist":"Shai Hulud","support":"","city":"Southampton","country":"UK","venue":"The Brook","tour":"EUROPE SUMMER 2026","ticketUrl":"https://lnk.to/SH-SOUTHAMPTON26"},
  {"date":"2026-07-06","artist":"Shai Hulud","support":"","city":"Leeds","country":"UK","venue":"Boom","tour":"EUROPE SUMMER 2026","ticketUrl":"https://lnk.to/SH-LEEDS26"},
  {"date":"2026-07-07","artist":"Shai Hulud","support":"","city":"Liverpool","country":"UK","venue":"Jacaranda","tour":"EUROPE SUMMER 2026","ticketUrl":"https://lnk.to/SH-LIVERPOOL26"},
  {"date":"2026-07-08","artist":"Shai Hulud","support":"","city":"Bridgend","country":"UK","venue":"The Black Cat","tour":"EUROPE SUMMER 2026","ticketUrl":"https://lnk.to/SH-BRIDGEND26"},
  {"date":"2026-07-09","artist":"Shai Hulud","support":"","city":"London","country":"UK","venue":"New Cross Inn","tour":"EUROPE SUMMER 2026","ticketUrl":"https://lnk.to/SH-LONDON26"},
  {"date":"2026-07-11","artist":"Shai Hulud","support":"","city":"Ludenscheid","country":"Germany","venue":"HHF Summer Brawl","tour":"EUROPE SUMMER 2026","ticketUrl":""},

  // === CONTENTION - NUCLEAR SUMMER EUROPE 2026 ===
  {"date":"2026-06-25","artist":"Contention","support":"Clique","city":"London","country":"UK","venue":"New Cross Inn","tour":"Nuclear Summer Europe 2026","ticketUrl":"https://lnk.to/CONTENTION-LONDON26"},
  {"date":"2026-06-27","artist":"Contention","support":"Clique","city":"Rennes","country":"France","venue":"Superbowl of Hardcore","tour":"Nuclear Summer Europe 2026","ticketUrl":"https://www.helloasso.com/associations/face-to-face/evenements/superbowl-of-hardcore-festival-2026"},
  {"date":"2026-06-28","artist":"Contention","support":"Clique","city":"Paris","country":"France","venue":"Le Chinois","tour":"Nuclear Summer Europe 2026","ticketUrl":"https://lnk.to/CONTENTION-PARIS26"},
  {"date":"2026-06-29","artist":"Contention","support":"Clique","city":"Esslingen","country":"Germany","venue":"Komma","tour":"Nuclear Summer Europe 2026","ticketUrl":"https://lnk.to/CONTENTION-ESSLINGEN26"},
  {"date":"2026-06-30","artist":"Contention","support":"Clique","city":"Lyon","country":"France","venue":"Warm Audio","tour":"Nuclear Summer Europe 2026","ticketUrl":"https://lnk.to/CONTENTION-LYON26"},
  {"date":"2026-07-01","artist":"Contention","support":"Clique","city":"San Dona di Piave","country":"Italy","venue":"Garage Guingette","tour":"Nuclear Summer Europe 2026","ticketUrl":"https://lnk.to/CONTENTION-VENICE26"},
  {"date":"2026-07-02","artist":"Contention","support":"Clique","city":"Neunkirchen","country":"Germany","venue":"Stummsche Reithalle","tour":"Nuclear Summer Europe 2026","ticketUrl":"https://lnk.to/SH-NEUNKIRCHEN26"},
  {"date":"2026-07-03","artist":"Contention","support":"Clique","city":"Herford","country":"Germany","venue":"SZ FLA FLA","tour":"Nuclear Summer Europe 2026","ticketUrl":"https://lnk.to/CONTENTION-HERFORD26"},
  {"date":"2026-07-04","artist":"Contention","support":"Clique","city":"Dordrecht","country":"Netherlands","venue":"Bibelot","tour":"Nuclear Summer Europe 2026","ticketUrl":"https://lnk.to/CONTENTION-DORDRECHT26"},
  {"date":"2026-07-05","artist":"Contention","support":"Clique","city":"Ypres","country":"Belgium","venue":"Ieper Fest","tour":"Nuclear Summer Europe 2026","ticketUrl":"https://shop.ticket.monster/event/ieperfest-2026-4ykvwm"},

  // === CONVERGE - EUROPE SUMMER 2026 ===
  {"date":"2026-06-25","artist":"Converge","support":"Heriot, Boneflower, Crouch","city":"Ysselsteyn","country":"Netherlands","venue":"Jera On Air","tour":"Europe Summer 2026","ticketUrl":"https://www.jeraonair.nl/"},
  {"date":"2026-06-26","artist":"Converge","support":"Heriot, Boneflower, Crouch","city":"Rennes","country":"France","venue":"Superbowl Of Hardcore","tour":"Europe Summer 2026","ticketUrl":"http://www.avocadobooking.com/avocms/www.instagram.com/superbowlofhardcorefestival/"},
  {"date":"2026-06-27","artist":"Converge","support":"Heriot, Boneflower, Crouch","city":"Manchester","country":"UK","venue":"Outbreak","tour":"Europe Summer 2026","ticketUrl":"https://www.outbreak-fest.co.uk/"},
  {"date":"2026-06-28","artist":"Converge","support":"Heriot, Boneflower, Crouch","city":"Antwerp","country":"Belgium","venue":"Zappa","tour":"Europe Summer 2026","ticketUrl":"https://lnk.to/CONVERGE-ANTWERP26"},
  {"date":"2026-06-29","artist":"Converge","support":"Heriot, Boneflower, Crouch","city":"Cologne","country":"Germany","venue":"Essigfabrik","tour":"Europe Summer 2026","ticketUrl":"https://lnk.to/CONVERGE-COLOGNE26"},
  {"date":"2026-06-30","artist":"Converge","support":"Heriot, Boneflower, Crouch","city":"Berlin","country":"Germany","venue":"SO36","tour":"Europe Summer 2026","ticketUrl":"https://lnk.to/CONVERGE-BERLIN26"},
  {"date":"2026-07-01","artist":"Converge","support":"Heriot, Boneflower, Crouch","city":"Trutnov","country":"Czech Republic","venue":"Obscene Extreme","tour":"Europe Summer 2026","ticketUrl":"https://www.obsceneextreme.cz/"},
  {"date":"2026-07-02","artist":"Converge","support":"Heriot, Boneflower, Crouch","city":"Vienna","country":"Austria","venue":"Arena","tour":"Europe Summer 2026","ticketUrl":"https://lnk.to/CONVERGE-VIENNA26"},
  {"date":"2026-07-03","artist":"Converge","support":"Heriot, Boneflower, Crouch","city":"Milan","country":"Italy","venue":"Circolo Magnolia Open Air","tour":"Europe Summer 2026","ticketUrl":"https://lnk.to/CONVERGE-MILAN26"},
  {"date":"2026-07-04","artist":"Converge","support":"Heriot, Boneflower, Crouch","city":"Viveiro","country":"Spain","venue":"Resurrection","tour":"Europe Summer 2026","ticketUrl":"https://www.resurrectionfest.es/"},

  // === CRYPTOPSY - MALICIOUS & VILE EUROPE SUMMER 2026 ===
  {"date":"2026-07-25","artist":"Cryptopsy","support":"","city":"Steenwijk","country":"Netherlands","venue":"Stonehenge Festival","tour":"Malicious & Vile Europe Summer 2026","ticketUrl":"https://www.stonehengefestival.nl/"},
  {"date":"2026-07-26","artist":"Cryptopsy","support":"Vulvodynia","city":"Cham","country":"Germany","venue":"LA","tour":"Malicious & Vile Europe Summer 2026","ticketUrl":"http://lnk.to/Cryptopsy26-Cham"},
  {"date":"2026-07-28","artist":"Cryptopsy","support":"","city":"Brasov","country":"Romania","venue":"Rockstadt Extreme Fest","tour":"Malicious & Vile Europe Summer 2026","ticketUrl":"https://rockstadtextremefest.ro/"},
  {"date":"2026-07-29","artist":"Cryptopsy","support":"Bleed From Within","city":"Kosice","country":"Slovakia","venue":"Collosseum","tour":"Malicious & Vile Europe Summer 2026","ticketUrl":"http://lnk.to/Cryptopsy26-Kosice"},
  {"date":"2026-07-30","artist":"Cryptopsy","support":"Vulvodynia","city":"Krakow","country":"Poland","venue":"Hype Park","tour":"Malicious & Vile Europe Summer 2026","ticketUrl":"http://lnk.to/Cryptopsy26-Krakow"},
  {"date":"2026-07-31","artist":"Cryptopsy","support":"","city":"Löbnitz","country":"Germany","venue":"Full Rewind","tour":"Malicious & Vile Europe Summer 2026","ticketUrl":"https://full-rewind.de/"},
  {"date":"2026-08-01","artist":"Cryptopsy","support":"","city":"Dortmund","country":"Germany","venue":"Dortmund Deathfest","tour":"Malicious & Vile Europe Summer 2026","ticketUrl":"https://dortmund-deathfest.de/"},
  {"date":"2026-08-02","artist":"Cryptopsy","support":"Celestial Sanctuary","city":"Brighton","country":"UK","venue":"Chalk","tour":"Malicious & Vile Europe Summer 2026","ticketUrl":"http://lnk.to/Cryptopsy26-Brighton"},
  {"date":"2026-08-03","artist":"Cryptopsy","support":"Celestial Sanctuary","city":"Cardiff","country":"UK","venue":"The Globe","tour":"Malicious & Vile Europe Summer 2026","ticketUrl":"http://lnk.to/Cryptopsy26-Cardiff"},
  {"date":"2026-08-05","artist":"Cryptopsy","support":"Celestial Sanctuary","city":"Dublin","country":"Ireland","venue":"Whelans","tour":"Malicious & Vile Europe Summer 2026","ticketUrl":"http://lnk.to/Cryptopsy26-Dublin"},
  {"date":"2026-08-06","artist":"Cryptopsy","support":"","city":"Derby","country":"UK","venue":"Bloodstock Open Air","tour":"Malicious & Vile Europe Summer 2026","ticketUrl":"https://bloodstock.uk.com/"},
  {"date":"2026-08-07","artist":"Cryptopsy","support":"","city":"Helsinki","country":"Finland","venue":"Hellsinki Metal Fest","tour":"Malicious & Vile Europe Summer 2026","ticketUrl":"https://hellsinkimetalfestival.fi/"},
  {"date":"2026-08-08","artist":"Cryptopsy","support":"","city":"Jaromer","country":"Czech Republic","venue":"Brutal Assault","tour":"Malicious & Vile Europe Summer 2026","ticketUrl":"https://brutalassault.cz/en"},
  {"date":"2026-08-09","artist":"Cryptopsy","support":"","city":"Vagos","country":"Portugal","venue":"Vagos Metal Fest","tour":"Malicious & Vile Europe Summer 2026","ticketUrl":"https://vagosmetalfest.com/"},
  {"date":"2026-08-12","artist":"Cryptopsy","support":"Revocation, Internal Bleeding","city":"Trier","country":"Germany","venue":"The Forum","tour":"Malicious & Vile Europe Summer 2026","ticketUrl":"http://lnk.to/Cryptopsy26-Trier"},
  {"date":"2026-08-13","artist":"Cryptopsy","support":"","city":"Dinkelsbühl","country":"Germany","venue":"Summer Breeze","tour":"Malicious & Vile Europe Summer 2026","ticketUrl":"https://www.summer-breeze.de/"},
  {"date":"2026-08-14","artist":"Cryptopsy","support":"","city":"Colmar","country":"France","venue":"Spirit In Black Festival","tour":"Malicious & Vile Europe Summer 2026","ticketUrl":"http://lnk.to/SpiritInBlackFest"},
  {"date":"2026-08-15","artist":"Cryptopsy","support":"","city":"Kortrijk","country":"Belgium","venue":"DVG Club","tour":"Malicious & Vile Europe Summer 2026","ticketUrl":"http://lnk.to/Cryptopsy26-Kortrijk"},
  {"date":"2026-08-16","artist":"Cryptopsy","support":"","city":"Carhaix","country":"France","venue":"Motocultor","tour":"Malicious & Vile Europe Summer 2026","ticketUrl":"https://www.motocultor-festival.com/"},
  {"date":"2026-08-18","artist":"Cryptopsy","support":"","city":"Martigny","country":"Switzerland","venue":"Sunset Bar","tour":"Malicious & Vile Europe Summer 2026","ticketUrl":"http://lnk.to/Cryptopsy26-Martigny"},
  {"date":"2026-08-19","artist":"Cryptopsy","support":"","city":"Pinarella Di Cervia","country":"Italy","venue":"Rockplanet","tour":"Malicious & Vile Europe Summer 2026","ticketUrl":"http://lnk.to/Cryptopsy26-Pinarella"},
  {"date":"2026-08-20","artist":"Cryptopsy","support":"","city":"Spital Am Semmering","country":"Austria","venue":"Kaltenbach Open Air","tour":"Malicious & Vile Europe Summer 2026","ticketUrl":"https://kaltenbach-openair.at/en/"},
  {"date":"2026-08-21","artist":"Cryptopsy","support":"","city":"Litomerice","country":"Czech Republic","venue":"Death Coffee Party","tour":"Malicious & Vile Europe Summer 2026","ticketUrl":"https://deathcoffee.cz/"},

  // === THY ART IS MURDER - EUROPE SUMMER 2026 ===
  {"date":"2026-07-29","artist":"Thy Art Is Murder","support":"","city":"Brasov","country":"Romania","venue":"Rockstadt Extreme Fest","tour":"Europe Summer 2026","ticketUrl":"https://rockstadtextremefest.ro/"},
  {"date":"2026-07-31","artist":"Thy Art Is Murder","support":"","city":"Manchester","country":"UK","venue":"Radar Fest","tour":"Europe Summer 2026","ticketUrl":"https://www.radarfestival.co.uk/"},
  {"date":"2026-08-01","artist":"Thy Art Is Murder","support":"","city":"Wacken","country":"Germany","venue":"Wacken Open Air","tour":"Europe Summer 2026","ticketUrl":"https://www.wacken.com/"},
  {"date":"2026-08-02","artist":"Thy Art Is Murder","support":"Fit For An Autopsy, Chelsea Grin","city":"Rostock","country":"Germany","venue":"Mau Club","tour":"Europe Summer 2026","ticketUrl":"https://lnk.to/TAIM-ROSTOCK26"},
  {"date":"2026-08-03","artist":"Thy Art Is Murder","support":"","city":"Leipzig","country":"Germany","venue":"Haus Auensee","tour":"Europe Summer 2026","ticketUrl":"https://www.eventim.de/artist/lamb-of-god/"},
  {"date":"2026-08-04","artist":"Thy Art Is Murder","support":"Fit For An Autopsy, Chelsea Grin, Protest The Hero","city":"Berlin","country":"Germany","venue":"Metropol","tour":"Europe Summer 2026","ticketUrl":"https://lnk.to/TAIM-BERLIN26"},
  {"date":"2026-08-05","artist":"Thy Art Is Murder","support":"Chelsea Grin","city":"Warsaw","country":"Poland","venue":"Progresja","tour":"Europe Summer 2026","ticketUrl":"https://lnk.to/TAIM-WARSAW26"},
  {"date":"2026-08-06","artist":"Thy Art Is Murder","support":"","city":"Jaromer","country":"Czech Republic","venue":"Brutal Assault","tour":"Europe Summer 2026","ticketUrl":"https://brutalassault.cz/"},
  {"date":"2026-08-07","artist":"Thy Art Is Murder","support":"","city":"Kortrijk","country":"Belgium","venue":"Alcatraz","tour":"Europe Summer 2026","ticketUrl":"https://www.alcatraz.be/"},
  {"date":"2026-08-08","artist":"Thy Art Is Murder","support":"","city":"Hamburg","country":"Germany","venue":"Elbriot","tour":"Europe Summer 2026","ticketUrl":"https://www.elbriot.de/"},
  {"date":"2026-08-09","artist":"Thy Art Is Murder","support":"","city":"Gothenburg","country":"Sweden","venue":"Pustervik","tour":"Europe Summer 2026","ticketUrl":"https://lnk.to/TAIM-GOTHENBURG26"},
  {"date":"2026-08-11","artist":"Thy Art Is Murder","support":"","city":"Copenhagen","country":"Denmark","venue":"KB Hallen","tour":"Europe Summer 2026","ticketUrl":"https://www.livenation.dk/en/event/lamb-of-god-frederiksberg-tickets-edp1637054"},
  {"date":"2026-08-12","artist":"Thy Art Is Murder","support":"Fit For An Autopsy, Chelsea Grin, Signs Of The Swarm","city":"Wiesbaden","country":"Germany","venue":"Schlachthof","tour":"Europe Summer 2026","ticketUrl":"https://lnk.to/TAIM-WIESBADEN26"},
  {"date":"2026-08-13","artist":"Thy Art Is Murder","support":"","city":"Sulingen","country":"Germany","venue":"Reload","tour":"Europe Summer 2026","ticketUrl":"https://reload-festival.de/"},
  {"date":"2026-08-14","artist":"Thy Art Is Murder","support":"","city":"Eindhoven","country":"Netherlands","venue":"Dynamo Metalfest","tour":"Europe Summer 2026","ticketUrl":"https://dynamo-metalfest.nl/"},
  {"date":"2026-08-15","artist":"Thy Art Is Murder","support":"","city":"Dinkelsbühl","country":"Germany","venue":"Summer Breeze","tour":"Europe Summer 2026","ticketUrl":"https://www.summer-breeze.de/"},

  // === THE AMITY AFFLICTION - EUROPE 2026 ===
  {"date":"2026-09-18","artist":"The Amity Affliction","support":"Silent Planet, Varials, Orthodox","city":"Wiesbaden","country":"Germany","venue":"Schlachthof","tour":"Europe 2026","ticketUrl":"https://lnk.to/TAA-WIESBADEN26"},
  {"date":"2026-09-19","artist":"The Amity Affliction","support":"Silent Planet, Varials, Orthodox","city":"Cologne","country":"Germany","venue":"Palladium","tour":"Europe 2026","ticketUrl":"https://lnk.to/TAA-COLOGNE26"},
  {"date":"2026-09-20","artist":"The Amity Affliction","support":"Silent Planet, Varials, Orthodox","city":"Hamburg","country":"Germany","venue":"Grosse Freiheit 36","tour":"Europe 2026","ticketUrl":"https://lnk.to/TAA-HAMBURG26"},
  {"date":"2026-09-22","artist":"The Amity Affliction","support":"Silent Planet, Varials, Orthodox","city":"Stockholm","country":"Sweden","venue":"Fållan","tour":"Europe 2026","ticketUrl":"https://lnk.to/TAA-STOCKHOLM26"},
  {"date":"2026-09-24","artist":"The Amity Affliction","support":"Silent Planet, Varials, Orthodox","city":"Helsinki","country":"Finland","venue":"Ääniwalli","tour":"Europe 2026","ticketUrl":"https://lnk.to/TAA-HELSINKI26"},
  {"date":"2026-09-26","artist":"The Amity Affliction","support":"Silent Planet, Varials, Orthodox","city":"Oslo","country":"Norway","venue":"Rockefeller","tour":"Europe 2026","ticketUrl":"https://lnk.to/TAA-OSLO26"},
  {"date":"2026-09-27","artist":"The Amity Affliction","support":"Silent Planet, Varials, Orthodox","city":"Copenhagen","country":"Denmark","venue":"Vega","tour":"Europe 2026","ticketUrl":"https://lnk.to/TAA-COPENHAGEN26"},
  {"date":"2026-09-28","artist":"The Amity Affliction","support":"Silent Planet, Varials, Orthodox","city":"Berlin","country":"Germany","venue":"Huxleys","tour":"Europe 2026","ticketUrl":"https://lnk.to/TAA-BERLIN26"},
  {"date":"2026-09-29","artist":"The Amity Affliction","support":"Silent Planet, Varials, Orthodox","city":"Warsaw","country":"Poland","venue":"Progresja","tour":"Europe 2026","ticketUrl":"https://lnk.to/TAA-WARSAW26"},
  {"date":"2026-10-01","artist":"The Amity Affliction","support":"Silent Planet, Varials, Orthodox","city":"Prague","country":"Czech Republic","venue":"Roxy","tour":"Europe 2026","ticketUrl":"https://lnk.to/TAA-PRAGUE26"},
  {"date":"2026-10-02","artist":"The Amity Affliction","support":"Silent Planet, Varials, Orthodox","city":"Vienna","country":"Austria","venue":"Gasometer","tour":"Europe 2026","ticketUrl":"https://lnk.to/TAA-VIENNA26"},
  {"date":"2026-10-03","artist":"The Amity Affliction","support":"Silent Planet, Varials, Orthodox","city":"Munich","country":"Germany","venue":"Tonhalle","tour":"Europe 2026","ticketUrl":"https://lnk.to/TAA-MUNICH26"},
  {"date":"2026-10-05","artist":"The Amity Affliction","support":"Silent Planet, Varials, Orthodox","city":"Zurich","country":"Switzerland","venue":"Komplex 457","tour":"Europe 2026","ticketUrl":"https://lnk.to/TAA-ZURICH26"},
  {"date":"2026-10-06","artist":"The Amity Affliction","support":"Silent Planet, Varials, Orthodox","city":"Paris","country":"France","venue":"Elysée Montmartre","tour":"Europe 2026","ticketUrl":"https://lnk.to/TAA-PARIS26"},
  {"date":"2026-10-07","artist":"The Amity Affliction","support":"Silent Planet, Varials, Orthodox","city":"Antwerp","country":"Belgium","venue":"Zappa","tour":"Europe 2026","ticketUrl":"https://lnk.to/TAA-ANTWERP26"},
  {"date":"2026-10-08","artist":"The Amity Affliction","support":"Silent Planet, Varials, Orthodox","city":"Tilburg","country":"Netherlands","venue":"0 1 3","tour":"Europe 2026","ticketUrl":"https://lnk.to/TAA-TILBURG26"},
  {"date":"2026-10-10","artist":"The Amity Affliction","support":"Silent Planet, Varials, Orthodox","city":"Manchester","country":"UK","venue":"o2 Ritz","tour":"Europe 2026","ticketUrl":"https://lnk.to/TAA-MANCHESTER26"},
  {"date":"2026-10-11","artist":"The Amity Affliction","support":"Silent Planet, Varials, Orthodox","city":"London","country":"UK","venue":"o2 Forum Kentish Town","tour":"Europe 2026","ticketUrl":"https://lnk.to/TAA-LONDON26"},
  {"date":"2026-10-12","artist":"The Amity Affliction","support":"Silent Planet, Varials, Orthodox","city":"Nottingham","country":"UK","venue":"Rock City","tour":"Europe 2026","ticketUrl":"https://lnk.to/TAA-NOTTINGHAM26"},
  {"date":"2026-10-13","artist":"The Amity Affliction","support":"Silent Planet, Varials, Orthodox","city":"Bristol","country":"UK","venue":"O2 Academy","tour":"Europe 2026","ticketUrl":"https://lnk.to/TAA-BRISTOL26"},

  // === HUMANITY'S LAST BREATH - EUROPEAN TOUR 2026 ===
  {"date":"2026-09-25","artist":"Humanity's Last Breath","support":"Vildhjarta, Enterprise Earth, Karmanjakah","city":"Berlin","country":"Germany","venue":"Hole44","tour":"European Tour 2026","ticketUrl":"http://lnk.to/HLB2026-Berlin"},
  {"date":"2026-09-26","artist":"Humanity's Last Breath","support":"Vildhjarta, Enterprise Earth, Karmanjakah","city":"Cologne","country":"Germany","venue":"Euroblast","tour":"European Tour 2026","ticketUrl":"https://www.euroblast.net/"},
  {"date":"2026-09-27","artist":"Humanity's Last Breath","support":"Vildhjarta, Enterprise Earth, Karmanjakah","city":"Leipzig","country":"Germany","venue":"Hellraiser","tour":"European Tour 2026","ticketUrl":"http://lnk.to/HLB2026-Leipzig"},
  {"date":"2026-09-28","artist":"Humanity's Last Breath","support":"Vildhjarta, Enterprise Earth, Karmanjakah","city":"Prague","country":"Czech Republic","venue":"Rock Cafe","tour":"European Tour 2026","ticketUrl":"http://lnk.to/HLB2026-Prague"},
  {"date":"2026-09-29","artist":"Humanity's Last Breath","support":"Vildhjarta, Enterprise Earth, Karmanjakah","city":"Vienna","country":"Austria","venue":"Szene","tour":"European Tour 2026","ticketUrl":"http://lnk.to/HLB2026-Vienna"},
  {"date":"2026-10-01","artist":"Humanity's Last Breath","support":"Vildhjarta, Enterprise Earth, Karmanjakah","city":"Munich","country":"Germany","venue":"Backstage Halle","tour":"European Tour 2026","ticketUrl":"http://lnk.to/HLB2026-Munich"},
  {"date":"2026-10-02","artist":"Humanity's Last Breath","support":"Vildhjarta, Enterprise Earth, Karmanjakah","city":"Milan","country":"Italy","venue":"Slaughter Club","tour":"European Tour 2026","ticketUrl":"http://lnk.to/HLB2026-Milan"},
  {"date":"2026-10-03","artist":"Humanity's Last Breath","support":"Vildhjarta, Enterprise Earth, Karmanjakah","city":"Aarau","country":"Switzerland","venue":"KiFF","tour":"European Tour 2026","ticketUrl":"http://lnk.to/HLB2026-Aarau"},
  {"date":"2026-10-04","artist":"Humanity's Last Breath","support":"Vildhjarta, Enterprise Earth, Karmanjakah","city":"Nuremberg","country":"Germany","venue":"Hirsch","tour":"European Tour 2026","ticketUrl":"http://lnk.to/HLB2026-Nuremberg"},
  {"date":"2026-10-05","artist":"Humanity's Last Breath","support":"Vildhjarta, Enterprise Earth, Karmanjakah","city":"Stuttgart","country":"Germany","venue":"Im Wizemann","tour":"European Tour 2026","ticketUrl":"http://lnk.to/HLB2026-Stuttgart"},
  {"date":"2026-10-06","artist":"Humanity's Last Breath","support":"Vildhjarta, Enterprise Earth, Karmanjakah","city":"Paris","country":"France","venue":"Petit Bain","tour":"European Tour 2026","ticketUrl":"http://lnk.to/HLB2026-Paris"},
  {"date":"2026-10-08","artist":"Humanity's Last Breath","support":"Vildhjarta, Enterprise Earth, Karmanjakah","city":"London","country":"UK","venue":"O2 Academy Islington","tour":"European Tour 2026","ticketUrl":"http://lnk.to/HLB2026-London"},
  {"date":"2026-10-09","artist":"Humanity's Last Breath","support":"Vildhjarta, Enterprise Earth, Karmanjakah","city":"Birmingham","country":"UK","venue":"Asylum","tour":"European Tour 2026","ticketUrl":"http://lnk.to/HLB2026-Birmingham"},
  {"date":"2026-10-10","artist":"Humanity's Last Breath","support":"Vildhjarta, Enterprise Earth, Karmanjakah","city":"Manchester","country":"UK","venue":"The Bread Shed","tour":"European Tour 2026","ticketUrl":"http://lnk.to/HLB2026-Manchester"},
  {"date":"2026-10-11","artist":"Humanity's Last Breath","support":"Vildhjarta, Enterprise Earth, Karmanjakah","city":"Glasgow","country":"UK","venue":"Slay","tour":"European Tour 2026","ticketUrl":"http://lnk.to/HLB2026-Glasgow"},
  {"date":"2026-10-12","artist":"Humanity's Last Breath","support":"Vildhjarta, Enterprise Earth, Karmanjakah","city":"Nottingham","country":"UK","venue":"Rescue Rooms","tour":"European Tour 2026","ticketUrl":"http://lnk.to/HLB2026-Nottingham"},
  {"date":"2026-10-13","artist":"Humanity's Last Breath","support":"Vildhjarta, Enterprise Earth, Karmanjakah","city":"Bristol","country":"UK","venue":"The Fleece","tour":"European Tour 2026","ticketUrl":"http://lnk.to/HLB2026-Bristol"},
  {"date":"2026-10-15","artist":"Humanity's Last Breath","support":"Vildhjarta, Enterprise Earth, Karmanjakah","city":"Antwerp","country":"Belgium","venue":"Zappa","tour":"European Tour 2026","ticketUrl":"http://lnk.to/HLB2026-Antwerp"},
  {"date":"2026-10-16","artist":"Humanity's Last Breath","support":"Vildhjarta, Enterprise Earth, Karmanjakah","city":"Tilburg","country":"Netherlands","venue":"Poppodium 013","tour":"European Tour 2026","ticketUrl":"http://lnk.to/HLB2026-Tilburg"},
  {"date":"2026-10-17","artist":"Humanity's Last Breath","support":"Vildhjarta, Enterprise Earth, Karmanjakah","city":"Hamburg","country":"Germany","venue":"Markthalle","tour":"European Tour 2026","ticketUrl":"http://lnk.to/HLB2026-Hamburg"},
  {"date":"2026-10-18","artist":"Humanity's Last Breath","support":"Vildhjarta, Enterprise Earth, Karmanjakah","city":"Copenhagen","country":"Denmark","venue":"Pumpehuset","tour":"European Tour 2026","ticketUrl":"http://lnk.to/HLB2026-Copenhagen"},
  {"date":"2026-10-19","artist":"Humanity's Last Breath","support":"Vildhjarta, Enterprise Earth, Karmanjakah","city":"Gothenburg","country":"Sweden","venue":"Filmstudion","tour":"European Tour 2026","ticketUrl":"http://lnk.to/HLB2026-Gothenburg"},
  {"date":"2026-10-20","artist":"Humanity's Last Breath","support":"Vildhjarta, Enterprise Earth, Karmanjakah","city":"Oslo","country":"Norway","venue":"John Dee","tour":"European Tour 2026","ticketUrl":"http://lnk.to/HLB2026-Oslo"},
  {"date":"2026-10-22","artist":"Humanity's Last Breath","support":"Vildhjarta, Enterprise Earth, Karmanjakah","city":"Helsinki","country":"Finland","venue":"Tavastia","tour":"European Tour 2026","ticketUrl":"http://lnk.to/HLB2026-Helsinki"},
  {"date":"2026-10-24","artist":"Humanity's Last Breath","support":"Vildhjarta, Enterprise Earth, Karmanjakah","city":"Stockholm","country":"Sweden","venue":"Kollektivet Livet","tour":"European Tour 2026","ticketUrl":"http://lnk.to/HLB2026-Stockholm"},

  // === SHADOW OF INTENT - “IMPERIUM DELIRIUM” EUROPEAN TOUR 2026 ===
  {"date":"2026-09-25","artist":"Shadow Of Intent","support":"Aborted, Disembodied Tyrant, Soreption","city":"Munich","country":"Germany","venue":"Backstage Werk","tour":"“Imperium Delirium” European Tour 2026","ticketUrl":"http://lnk.to/SOI2026-Munich"},
  {"date":"2026-09-26","artist":"Shadow Of Intent","support":"Aborted, Disembodied Tyrant, Soreption","city":"Vienna","country":"Austria","venue":"SimmCity","tour":"“Imperium Delirium” European Tour 2026","ticketUrl":"http://lnk.to/SOI2026-Vienna"},
  {"date":"2026-09-27","artist":"Shadow Of Intent","support":"Aborted, Disembodied Tyrant, Soreption","city":"Karlsruhe","country":"Germany","venue":"Substage","tour":"“Imperium Delirium” European Tour 2026","ticketUrl":"http://lnk.to/SOI2026-Karlsruhe"},
  {"date":"2026-09-28","artist":"Shadow Of Intent","support":"Aborted, Disembodied Tyrant, Soreption","city":"Paris","country":"France","venue":"La Machine","tour":"“Imperium Delirium” European Tour 2026","ticketUrl":"http://lnk.to/SOI2026-Paris"},
  {"date":"2026-09-30","artist":"Shadow Of Intent","support":"Aborted, Disembodied Tyrant, Soreption","city":"Glasgow","country":"UK","venue":"The Garage","tour":"“Imperium Delirium” European Tour 2026","ticketUrl":"http://lnk.to/SOI2026-Glasgow"},
  {"date":"2026-10-01","artist":"Shadow Of Intent","support":"Aborted, Disembodied Tyrant, Soreption","city":"Manchester","country":"UK","venue":"Academy 2","tour":"“Imperium Delirium” European Tour 2026","ticketUrl":"http://lnk.to/SOI2026-Manchester"},
  {"date":"2026-10-02","artist":"Shadow Of Intent","support":"Aborted, Disembodied Tyrant, Soreption","city":"Bristol","country":"UK","venue":"The Prospect Building","tour":"“Imperium Delirium” European Tour 2026","ticketUrl":"http://lnk.to/SOI2026-Bristol"},
  {"date":"2026-10-03","artist":"Shadow Of Intent","support":"Aborted, Disembodied Tyrant, Soreption","city":"London","country":"UK","venue":"Electric Brixton","tour":"“Imperium Delirium” European Tour 2026","ticketUrl":"http://lnk.to/SOI2026-London"},
  {"date":"2026-10-04","artist":"Shadow Of Intent","support":"Aborted, Disembodied Tyrant, Soreption","city":"Antwerp","country":"Belgium","venue":"Zappa","tour":"“Imperium Delirium” European Tour 2026","ticketUrl":"http://lnk.to/SOI2026-Antwerp"},
  {"date":"2026-10-06","artist":"Shadow Of Intent","support":"Aborted, Disembodied Tyrant, Soreption","city":"Copenhagen","country":"Denmark","venue":"Amager Bio","tour":"“Imperium Delirium” European Tour 2026","ticketUrl":"http://lnk.to/SOI2026-Copenhagen"},
  {"date":"2026-10-07","artist":"Shadow Of Intent","support":"Aborted, Disembodied Tyrant, Soreption","city":"Hamburg","country":"Germany","venue":"Fabrik","tour":"“Imperium Delirium” European Tour 2026","ticketUrl":"http://lnk.to/SOI2026-Hamburg"},
  {"date":"2026-10-08","artist":"Shadow Of Intent","support":"Aborted, Disembodied Tyrant, Soreption","city":"Berlin","country":"Germany","venue":"Metropol","tour":"“Imperium Delirium” European Tour 2026","ticketUrl":"http://lnk.to/SOI2026-Berlin"},
  {"date":"2026-10-09","artist":"Shadow Of Intent","support":"Aborted, Disembodied Tyrant, Soreption","city":"Utrecht","country":"Netherlands","venue":"Tivoli Ronda","tour":"“Imperium Delirium” European Tour 2026","ticketUrl":"http://lnk.to/SOI2026-Utrecht"},
  {"date":"2026-10-10","artist":"Shadow Of Intent","support":"Aborted, Disembodied Tyrant, Soreption","city":"Cologne","country":"Germany","venue":"Essigfabrik","tour":"“Imperium Delirium” European Tour 2026","ticketUrl":"http://lnk.to/SOI2026-Cologne"},

];

const CITY_COORDS = {
  "Aarau": [47.39, 8.04],
  "Amsterdam": [52.37, 4.9],
  "Antwerp": [51.22, 4.4],
  "Barcelona": [41.39, 2.17],
  "Belfast": [54.6, -5.93],
  "Berlin": [52.52, 13.41],
  "Birmingham": [52.49, -1.89],
  "Bochum": [51.48, 7.22],
  "Bordeaux": [44.84, -0.58],
  "Brasov": [45.65, 25.61],
  "Bremen": [53.08, 8.8],
  "Bridgend": [51.51, -3.58],
  "Brighton": [50.82, -0.14],
  "Bristol": [51.45, -2.59],
  "Budapest": [47.5, 19.04],
  "Cardiff": [51.48, -3.18],
  "Carhaix": [48.28, -3.56],
  "Cartagena": [37.61, -0.99],
  "Cham": [49.22, 12.67],
  "Clisson": [47.09, -1.28],
  "Colmar": [48.08, 7.36],
  "Cologne": [50.94, 6.96],
  "Colombier-Saugnieu": [45.72, 5.1],
  "Copenhagen": [55.68, 12.57],
  "Cork": [51.9, -8.47],
  "Derby": [52.92, -1.48],
  "Dessel": [51.24, 5.11],
  "Dinkelsbühl": [49.07, 10.32],
  "Dischingen": [48.7, 10.35],
  "Donington": [52.83, -1.38],
  "Dordrecht": [51.81, 4.67],
  "Dortmund": [51.51, 7.47],
  "Dresden": [51.05, 13.74],
  "Dublin": [53.35, -6.26],
  "Eindhoven": [51.44, 5.47],
  "Esslingen": [48.74, 9.31],
  "Frankfurt": [50.11, 8.68],
  "Gdansk": [54.35, 18.65],
  "Geneva": [46.2, 6.14],
  "Glasgow": [55.86, -4.25],
  "Gothenburg": [57.71, 11.97],
  "Graz": [47.07, 15.44],
  "Haarlem": [52.38, 4.64],
  "Hamburg": [53.55, 9.99],
  "Hannover": [52.37, 9.74],
  "Hatfield": [51.76, -0.23],
  "Helsinki": [60.17, 24.94],
  "Herford": [52.11, 8.67],
  "Hoofddorp": [52.3, 4.69],
  "Hradec Kralove": [50.21, 15.83],
  "Innsbruck": [47.26, 11.39],
  "Jaromer": [50.36, 15.92],
  "Jena": [50.93, 11.59],
  "Karlsruhe": [49.01, 8.4],
  "Kortrijk": [50.83, 3.27],
  "Kosice": [48.72, 21.25],
  "Krakow": [50.05, 20],
  "Kyiv": [50.45, 30.52],
  "Landgraaf": [50.9, 6.02],
  "Leeds": [53.8, -1.55],
  "Leeuwarden": [53.2, 5.8],
  "Leipzig": [51.34, 12.37],
  "Lille": [50.63, 3.06],
  "Lindau": [47.55, 9.68],
  "Linz": [48.31, 14.29],
  "Lisbon": [38.72, -9.14],
  "Litomerice": [50.53, 14.13],
  "Liverpool": [53.41, -2.98],
  "Ljubljana": [46.06, 14.51],
  "London": [51.51, -0.13],
  "Ludenscheid": [51.22, 7.63],
  "Lund": [55.7, 13.19],
  "Lviv": [49.84, 24.03],
  "Lyon": [45.76, 4.84],
  "Löbnitz": [54.29, 12.72],
  "Madrid": [40.42, -3.7],
  "Manchester": [53.48, -2.24],
  "Martigny": [46.1, 7.07],
  "Milan": [45.46, 9.19],
  "Moers": [51.45, 6.63],
  "Monthey": [46.25, 6.95],
  "Munich": [48.14, 11.58],
  "Nantes": [47.22, -1.55],
  "Neunkirchen": [49.34, 7.18],
  "Newcastle": [54.98, -1.61],
  "Nickelsdorf": [47.93, 17.07],
  "Nottingham": [52.95, -1.15],
  "Nurburgring": [50.33, 6.94],
  "Nuremberg": [49.45, 11.08],
  "Oslo": [59.91, 10.75],
  "Paris": [48.86, 2.35],
  "Pinarella Di Cervia": [44.25, 12.37],
  "Plymouth": [50.38, -4.14],
  "Poznan": [52.41, 16.93],
  "Prague": [50.08, 14.44],
  "Querfurt": [51.38, 11.6],
  "Rennes": [48.11, -1.68],
  "Riga": [56.95, 24.11],
  "Rostock": [54.09, 12.14],
  "San Dona di Piave": [45.63, 12.57],
  "Schweinfurt": [50.04, 10.23],
  "Southampton": [50.9, -1.4],
  "Spital Am Semmering": [47.62, 15.75],
  "Steenwijk": [52.79, 6.12],
  "Stockholm": [59.33, 18.07],
  "Stuttgart": [48.78, 9.18],
  "Sulingen": [52.68, 8.8],
  "Swansea": [51.62, -3.94],
  "Tallinn": [59.44, 24.75],
  "Tampere": [61.5, 23.79],
  "Tilburg": [51.56, 5.09],
  "Torgau": [51.56, 13],
  "Torquay": [50.46, -3.53],
  "Toulouse": [43.6, 1.44],
  "Tours": [47.39, 0.69],
  "Trier": [49.76, 6.64],
  "Trutnov": [50.56, 15.91],
  "Utrecht": [52.09, 5.12],
  "Vagos": [40.55, -8.68],
  "Vechta": [52.73, 8.29],
  "Venice": [45.44, 12.32],
  "Vienna": [48.21, 16.37],
  "Vitoria": [42.85, -2.67],
  "Viveiro": [43.66, -7.6],
  "Wacken": [54.02, 9.38],
  "Warsaw": [52.23, 21.01],
  "Wiesbaden": [50.08, 8.24],
  "Ypres": [50.85, 2.89],
  "Ysselsteyn": [51.53, 5.94],
  "Zurich": [47.38, 8.54],
};

const TOUR_IMAGES = [
  {"artist":"Bodysnatcher","tour":"THE HELL IS HERE, HELL IS HOME TOUR","imageUrl":"http://www.avocadobooking.com/avocms/cache/com_zoo/images/BODYSNATCHER-EU2026-HEADER-alt_e9d4c97f6d63ae34a61510b3ec4eb644.jpg"},
  {"artist":"Cryptopsy","tour":"Malicious & Vile Europe Summer 2026","imageUrl":"http://www.avocadobooking.com/avocms/cache/com_zoo/images/Cryptopsy-EuropeSummer2026_HEADER_5352b5b71a1822abc96757ebdb667061.jpg"},
  {"artist":"Fit For A King","tour":"Lonely God European Tour 2026","imageUrl":"http://www.avocadobooking.com/avocms/cache/com_zoo/images/FFAK_EUSping26-Banner-981_596195d95e85e760a4ee4349575e48df.jpg"},
  {"artist":"Humanity's Last Breath","tour":"European Tour 2026","imageUrl":"http://www.avocadobooking.com/avocms/cache/com_zoo/images/HLB-2026-HEADER_21c12e15ee80bf2c551b27b45e9c0c7e.jpg"},
  {"artist":"Man With A Mission","tour":"‘MARKING NEW GROUND’ EUROPE SUMMER 2026","imageUrl":"http://www.avocadobooking.com/avocms/cache/com_zoo/images/MWAM_FullTour_EU26_Header_93a3db6a7fba55f9ee51e856a89ce410.jpg"},
  {"artist":"Paledusk","tour":"EU/UK Tour 2026","imageUrl":"http://www.avocadobooking.com/avocms/cache/com_zoo/images/Paledusk-Europe2026-HEADER_94c247d7026d655e5bc8c40329a12804.jpg"},
  {"artist":"Rivers Of Nihil","tour":"Europe Summer 2026","imageUrl":"http://www.avocadobooking.com/avocms/cache/com_zoo/images/RON-EU_Header_65d9a567148c1609bd987cca63557e86.jpg"},
  {"artist":"Silent Planet","tour":"EU/UK Summer 2026","imageUrl":"http://www.avocadobooking.com/avocms/cache/com_zoo/images/SilentPlanet_EUJune26_Banner_54db5edb0665040e9ecbde14c1006f72.jpg"},
  {"artist":"The Plot In You","tour":"Europe 2026","imageUrl":"http://www.avocadobooking.com/avocms/cache/com_zoo/images/TPIY-26_Banner_ffea523c834a6d65c29bca8ac868ce75.jpg"},
  {"artist":"Contention","tour":"Nuclear Summer Europe 2026","imageUrl":"http://www.avocadobooking.com/avocms/cache/com_zoo/images/Contention_Header_73eab93d9f6c86d17291f0c7c2138b52.jpg"},
  {"artist":"Crystal Lake & Miss May I","tour":"European Tour 2026","imageUrl":"http://www.avocadobooking.com/avocms/cache/com_zoo/images/CL-MMI-HEADER_26_c6da583237a9bac1bae33a4c823f5226.jpg"},
  {"artist":"French Police","tour":"Europe 2026","imageUrl":"http://www.avocadobooking.com/avocms/cache/com_zoo/images/FrenchPolice2026-HEADER-981_ec4075a27de6bb2ba848406afbcb12ae.jpg"},
  {"artist":"Kublai Khan TX","tour":"Europe Summer 2026","imageUrl":"http://www.avocadobooking.com/avocms/cache/com_zoo/images/KKTX_Banner_298038ecec4e1fa839dca709556894b2.jpg"},
  {"artist":"Morning Again","tour":"Europe 2026","imageUrl":"http://www.avocadobooking.com/avocms/cache/com_zoo/images/MorningAgain2026-Header_7a367f10427ff3a29daca3ab0dddbea1.jpg"},
  {"artist":"Queensrÿche","tour":"Europe Summer 2026","imageUrl":"http://www.avocadobooking.com/avocms/cache/com_zoo/images/Queensryche-2026_Banner_a054852653db27e680077fb5a1b9bdd7.jpg"},
  {"artist":"Shadow Of Intent","tour":"“Imperium Delirium” European Tour 2026","imageUrl":"http://www.avocadobooking.com/avocms/cache/com_zoo/images/SHADOWOFINTENT-EU2026_HEADER_ffd19b960c6dc8736b151debadf1c649.jpg"},
  {"artist":"Spaced","tour":"UK and Ireland 2026","imageUrl":"http://www.avocadobooking.com/avocms/cache/com_zoo/images/Spaced26_Header_645ae3d42149023506fc6de0e3b0c3c5.jpg"},
  {"artist":"Thrown","tour":"Baltics & Finland Tour 2026","imageUrl":"http://www.avocadobooking.com/avocms/cache/com_zoo/images/Thrown-26_Banner_62aa02c418ad6b587db93354548497de.jpg"},
  {"artist":"Converge","tour":"Europe Summer 2026","imageUrl":"http://www.avocadobooking.com/avocms/cache/com_zoo/images/Converge_2026_poster_621d2ee28c62a5d799028d8c27f03e56.jpg"},
  {"artist":"Excide","tour":"UK Summer 2026","imageUrl":"http://www.avocadobooking.com/avocms/cache/com_zoo/images/Excide-Header_aeaa1dea9ee19709f19734be176ed132.jpg"},
  {"artist":"Hands Like Houses & Broadside","tour":"EUROPEAN CO-HEADLINE TOUR 2026","imageUrl":"http://www.avocadobooking.com/avocms/cache/com_zoo/images/Broadside-HLH_Header_c903823cf577f7d3aa3d251ad5c19646.jpg"},
  {"artist":"Lost Society","tour":"Tour Is A State Of Mind","imageUrl":"http://www.avocadobooking.com/avocms/cache/com_zoo/images/LostSociety_Banner_acd39ca05b23d06b43205ee19e19a5ea.jpg"},
  {"artist":"Rain City Drive","tour":"Europe Summer 2026","imageUrl":"http://www.avocadobooking.com/avocms/cache/com_zoo/images/RCD-EU2026_BANNER_3a2836e4996fe4ebe2b34fd177b88271.jpg"},
  {"artist":"Shai Hulud","tour":"EUROPE SUMMER 2026","imageUrl":"http://www.avocadobooking.com/avocms/cache/com_zoo/images/ShaiHulud-26_Header_88ef1dbc268ff041e34f268966d96d19.jpg"},
  {"artist":"The Amity Affliction","tour":"Europe 2026","imageUrl":"http://www.avocadobooking.com/avocms/cache/com_zoo/images/TAA-FB_Banner-26_ca6943210d103c881e0fae8681c2a16e.jpg"},
  {"artist":"Thy Art Is Murder","tour":"Europe Summer 2026","imageUrl":"http://www.avocadobooking.com/avocms/cache/com_zoo/images/TAIM_EU2026Tour_Banner_c3a3c123e5ae38377e5489b32f445967.jpg"},
];
